# -*- coding: utf-8 -*-
u"""ข้อสอบ Part I และ Part II ของวิชาภาษาอังกฤษ ตามแนวข้อสอบที่อาจารย์ให้มา

Part I  · Vocabulary      10 คะแนน · A ศัพท์การตลาด 5 ข้อ · B ศัพท์ M&A 5 ข้อ
          รูปแบบ เลือกวลีจากกล่องคำมาเติมให้ประโยคสมบูรณ์
Part II · Language Points 10 คะแนน · A ลำดับคำในวลีนาม 5 ข้อ · B รูปกริยาคาดการณ์ 5 ข้อ
          รูปแบบ A ตัดสินว่าวลีเรียงถูกหรือไม่ · B เลือกรูปกริยาที่ถูก

ทุกข้อ 1 คะแนน ห้าชุด ใช้คู่กับ Part III ชุดเดียวกัน รวมชุดละ 40 คะแนน
ชุดที่ 6 ถึง 15 อยู่ใน exam-data-2.py เป็นแบบฝึกล้วน ไม่มี Part III

── บริบทเป็นธุรกิจทั่วไป ไม่ใช่งานบัญชีเฉพาะทาง ──
วิชานี้วัดภาษาอังกฤษธุรกิจ ไม่ได้วัดความรู้บัญชี ถ้าโจทย์พูดถึงการกระทบยอด
ค่าความนิยม หรือการรับรู้รายได้ คนที่ตอบผิดอาจจะแค่ไม่รู้ศัพท์บัญชี
ทั้งที่ภาษาแน่นพอแล้ว ซึ่งไม่ใช่สิ่งที่ข้อสอบนี้ตั้งใจวัด

บริบทจึงเป็นเรื่องที่คนทำงานบริษัทเจอทุกวัน คือ การขาย ลูกค้า คู่แข่ง
การเปิดตัวสินค้า สัญญา ซัพพลายเออร์ การส่งของ การประชุม และการเจรจาซื้อขายกิจการ
แค่ให้เข้ากับคำศัพท์ที่กำลังวัดก็พอ · tools/make-exam.py มีตัวตรวจคอยจับ
ไม่ให้ศัพท์บัญชีเฉพาะทางหลุดกลับเข้ามาอีก

ไม่ใช้ชื่อบริษัทจริงหรือดีลจริงเลย เพราะข้อสอบภาษาไม่ควรวัดว่าจำกรณีศึกษาได้ไหม
และความยาวประโยคคุมไว้ราว 12 ถึง 22 คำ ซึ่งเป็นระดับที่ upper intermediate อ่านจบในรอบเดียว
"""

# ── Part I · A ── เติมวลีศัพท์การตลาดจากกล่องคำ
# แต่ละชุดมีกล่องคำ 8 วลี แต่ใช้จริง 5 ข้อ ที่เหลือเป็นตัวลวง
P1A = [
 {'box': ['market research', 'market share', 'product launch', 'customer profile',
          'brand loyalty', 'market leader', 'brand awareness', 'price range'],
  'items': [
   ('The board refused to approve the plan until the ………… had been completed.',
    'market research',
    u'carry out หรือ complete คู่กับ market research เสมอ · ห้ามใช้ make'),
   ('Our ………… slipped from eighteen percent to fourteen after two new rivals arrived.',
    'market share',
    u'ตัวเลขเปอร์เซ็นต์ที่กิจการครองอยู่ คือส่วนแบ่งตลาด'),
   ('The ………… was put back by three months because the packaging was not ready.',
    'product launch',
    u'สิ่งที่เลื่อนได้และผูกกับความพร้อมของสินค้า คือการเปิดตัว'),
   ('Before we redesign the website, we need a clearer ………… of who actually buys from us.',
    'customer profile',
    u'ภาพลักษณะของกลุ่มลูกค้า ใช้เป็นฐานในการออกแบบอะไรก็ได้'),
   ('Buyers here switch supplier over a one percent price difference, so ………… is very low.',
    'brand loyalty',
    u'เปลี่ยนเจ้าเพราะราคาต่างกันนิดเดียว แปลว่าไม่ภักดีต่อแบรนด์'),
  ]},
 {'box': ['marketing mix', 'market segmentation', 'customer retention', 'product portfolio',
          'word of mouth', 'brand positioning', 'target market', 'market penetration'],
  'items': [
   ('The ………… covers product, price, place and promotion, and all four have to work together.',
    'marketing mix',
    u'สี่ P รวมกันเรียกว่าส่วนประสมการตลาด'),
   ('………… divides buyers into groups so that each group can be approached differently.',
    'Market segmentation',
    u'แบ่งผู้ซื้อออกเป็นกลุ่ม เพื่อออกแบบวิธีเข้าหาแต่ละกลุ่มแยกกัน'),
   ('Winning a new account costs us five times more than ………… does.',
    'customer retention',
    u'การรักษาลูกค้าเดิมถูกกว่าการหาลูกค้าใหม่มาก'),
   ('We now sell forty different items, and not every one of them earns its place in the ………… .',
    'product portfolio',
    u'ของทั้งหมดที่กิจการมีขาย เรียกรวมว่ากลุ่มผลิตภัณฑ์'),
   ('The firm spends nothing on advertising and has grown entirely through ………… .',
    'word of mouth',
    u'ไม่มีงบโฆษณาเลยแต่ยังโต คือโตด้วยการบอกต่อ'),
  ]},
 {'box': ['focus group', 'product feature', 'market adaptation', 'retail outlets',
          'brand extension', 'market niche', 'special offer', 'sales forecast'],
  'items': [
   ('We ran six ………… sessions and recorded what buyers said about the packaging.',
    'focus group',
    u'เชิญคนมานั่งคุยเป็นกลุ่มแล้วเก็บความเห็น'),
   ('The unique selling point is the one ………… that none of our competitors can copy.',
    'product feature',
    u'USP คือคุณสมบัติของสินค้าที่ไม่เหมือนใคร'),
   ('The recipe is too sweet for that country, so some ………… will be needed.',
    'market adaptation',
    u'ปรับตัวสินค้าให้เข้ากับตลาดปลายทาง'),
   ('Our distributor supplies eight thousand ………… , so keeping every shelf stocked is hard.',
    'retail outlets',
    u'ร้านค้าปลีกที่รับสินค้าไปขาย · ใช้รูปพหูพจน์เพราะมีแปดพันแห่ง'),
   ('Selling shampoo under our established soap name was a ………… that needed almost no new advertising.',
    'brand extension',
    u'เอาชื่อแบรนด์เดิมไปทำสินค้าประเภทใหม่ จึงไม่ต้องสร้างการรู้จักใหม่'),
  ]},
 {'box': ['questionnaire', 'market leader', 'advertising campaign', 'sales targets',
          'distributor', 'market sector', 'premium product', 'free samples'],
  'items': [
   ('Two thousand buyers completed our ………… , and the results came back last week.',
    'questionnaire',
    u'สิ่งที่คนกรอกตอบ คือแบบสอบถาม'),
   ('They hold thirty-one percent of the market, which makes them the ………… .',
    'market leader',
    u'ครองส่วนแบ่งสูงสุดคือผู้นำตลาด · ระวังอย่าเขียน marketing leader'),
   ('The ………… ran for six weeks across television and radio.',
    'advertising campaign',
    u'สิ่งที่มีระยะเวลาชัดเจนและลงหลายสื่อ คือแคมเปญโฆษณา'),
   ('None of the four regions met their ………… , so nobody received a bonus this year.',
    'sales targets',
    u'เป้ายอดขายที่ผูกกับโบนัส · ใช้รูปพหูพจน์เพราะมีหลายภูมิภาค'),
   ('We do not sell direct; a single ………… handles every order in that country.',
    'distributor',
    u'ผู้จัดจำหน่ายที่รับสินค้าไปกระจายต่อ'),
  ]},
 {'box': ['marketing strategy', 'product range', 'brand image', 'advertising budget',
          'sales figures', 'price war', 'market penetration', 'product lifecycle'],
  'items': [
   ('The board approved the ………… for next year but cut the spend by twelve percent.',
    'advertising budget',
    u'ตัวเลขที่คณะกรรมการอนุมัติแล้วตัดลงได้ คืองบโฆษณา'),
   ('The ………… for the first half were released to the press on Thursday.',
    'sales figures',
    u'ตัวเลขยอดขายที่เปิดเผยต่อสาธารณะ · ใช้รูปพหูพจน์เสมอ'),
   ('Cutting the price would damage our ………… , which took ten years to build.',
    'brand image',
    u'ภาพลักษณ์ของแบรนด์ที่สะสมมานาน เสียได้ง่ายจากการลดราคา'),
   ('We have narrowed the ………… from sixty items to twenty to make the warehouse easier to run.',
    'product range',
    u'ช่วงสินค้าที่กิจการมีขาย · ลดจำนวนรายการเพื่อให้จัดการง่ายขึ้น'),
   ('Every department has to work to the same ………… , which the board signs off each March.',
    'marketing strategy',
    u'แผนหลักทางการตลาดที่ทุกฝ่ายต้องเดินตาม'),
  ]},
]

# ── Part I · B ── เติมวลีศัพท์การควบรวมและซื้อกิจการจากกล่องคำ
# ไม่ใช้ชื่อบริษัทจริง ทุกกรณีสมมติขึ้นใหม่ และเล่าเป็นเรื่องธุรกิจ ไม่ใช่งานบัญชี
P1B = [
 {'box': ['made a bid', 'rejected the bid', 'hostile takeover', 'due diligence',
          'management buyout', 'took a stake', 'joint venture', 'synergies'],
  'items': [
   ('In March a European group ………… for our biggest rival worth about four hundred million euros.',
    'made a bid',
    u'make a bid for คือยื่นข้อเสนอซื้อ · ระวังรูปกริยาในอดีตด้วย'),
   ('The board ………… within a week, saying the offer was far too low.',
    'rejected the bid',
    u'ปฏิเสธข้อเสนอเพราะเห็นว่าราคาต่ำเกินไป'),
   ('Because the directors refused to recommend it, the approach became a ………… .',
    'hostile takeover',
    u'คณะกรรมการคัดค้าน ผู้ซื้อจึงเสนอกับผู้ถือหุ้นโดยตรง'),
   ('During ………… the buyer discovered that the main supply contract was about to expire.',
    'due diligence',
    u'ขั้นตรวจสอบสถานะกิจการก่อนซื้อ · เป็นตอนที่ผู้ซื้อได้เห็นสัญญาและข้อมูลภายในจริง'),
   ('Four senior managers borrowed heavily to buy the division they had been running, in a ………… .',
    'management buyout',
    u'ผู้บริหารกู้เงินมาซื้อกิจการที่ตนบริหารอยู่'),
  ]},
 {'box': ['took a stake', 'joint venture', 'synergies', 'merger', 'target company',
          'asset stripping', 'white knight', 'subsidiary'],
  'items': [
   ('The investor quietly ………… of eight percent before anyone noticed.',
    'took a stake',
    u'take a stake in คือเข้าถือหุ้นบางส่วน · แปดเปอร์เซ็นต์ยังไม่ถึงขั้นเข้าควบคุม'),
   ('The two firms each put in half the capital and formed a ………… to build the plant.',
    'joint venture',
    u'ทั้งคู่ยังอยู่และเป็นเจ้าของร่วมในกิจการใหม่'),
   ('The plan assumed ………… of sixty million a year from running one head office instead of two.',
    'synergies',
    u'ประโยชน์ที่คาดว่าจะได้จากการรวมกัน ซึ่งมักถูกประมาณการไว้สูงเกินจริง'),
   ('Both companies were of a similar size, so the deal was presented as a ………… of equals.',
    'merger',
    u'ควบรวมระหว่างกิจการที่มีฐานะใกล้เคียงกัน'),
   ('Once the deal closed, the smaller firm became a wholly owned ………… .',
    'subsidiary',
    u'กิจการที่ถูกถือหุ้นทั้งหมด ยังดำเนินงานต่อภายใต้เจ้าของใหม่'),
  ]},
 {'box': ['friendly takeover', 'predator', 'asset stripping', 'white knight',
          'shareholders', 'acquisition', 'valuation', 'integration'],
  'items': [
   ('The board welcomed the offer and recommended it, so this was a ………… .',
    'friendly takeover',
    u'คณะกรรมการเห็นชอบ ตรงข้ามกับ hostile takeover'),
   ('A second buyer appeared on better terms, and the directors treated it as a ………… .',
    'white knight',
    u'ผู้ซื้อรายที่เข้ามาช่วยกิจการเป้าหมายให้พ้นจากข้อเสนอที่ไม่ต้องการ'),
   ('The buyer sold the warehouses within a year, which the press called ………… .',
    'asset stripping',
    u'ซื้อมาแล้วแยกขายสินทรัพย์เอากำไร ไม่ได้ตั้งใจดำเนินกิจการต่อ'),
   ('The ………… put on the business was eight times its annual profit, which our team thought was too high.',
    'valuation',
    u'การตีมูลค่ากิจการ มักอ้างอิงตัวคูณกำไร'),
   ('The ………… approved the deal at a meeting held in November.',
    'shareholders',
    u'ผู้ถือหุ้นเป็นผู้อนุมัติ ไม่ใช่ฝ่ายบริหาร'),
  ]},
 {'box': ['takeover bid', 'due diligence', 'acquisition', 'divested', 'integration',
          'predator', 'merger', 'stake'],
  'items': [
   ('The group ………… its loss-making logistics arm in order to fund the purchase.',
    'divested',
    u'ขายธุรกิจบางส่วนออกไป มักทำเพื่อหาเงินมาซื้อกิจการอื่น'),
   ('Bringing the two sales teams together took two years, and ………… cost far more than anyone expected.',
    'integration',
    u'การรวมทีมและระบบหลังปิดดีล มักใช้เวลาและเงินมากกว่าที่วางแผนไว้'),
   ('The ………… lapsed because fewer than half the shareholders accepted it.',
    'takeover bid',
    u'ข้อเสนอซื้อกิจการที่ตกไปเพราะผู้ถือหุ้นตอบรับไม่ถึงเกณฑ์'),
   ('The ………… was completed in September, and the two head offices merged in November.',
    'acquisition',
    u'การซื้อกิจการ · หลังปิดดีลจึงเริ่มรวมสำนักงานเข้าด้วยกัน'),
   ('The fund increased its ………… from twelve percent to twenty-nine percent in two months.',
    'stake',
    u'สัดส่วนการถือหุ้น เพิ่มขึ้นได้โดยยังไม่ถึงขั้นครอบงำกิจการ'),
  ]},
 {'box': ['bid', 'merged', 'due diligence', 'synergies', 'joint venture',
          'hostile', 'stake', 'buyout'],
  'items': [
   ('The two engineering firms ………… last year and now operate under a single name.',
    'merged',
    u'รวมกิจการเข้าด้วยกันแล้วใช้ชื่อเดียว'),
   ('The team had only three weeks to complete ………… , which was far too short.',
    'due diligence',
    u'เวลาที่น้อยเกินไปสำหรับการตรวจสอบสถานะกิจการ คือความเสี่ยงคลาสสิกของดีล'),
   ('After two rejections the approach turned ………… and went straight to the shareholders.',
    'hostile',
    u'เมื่อคณะกรรมการปฏิเสธ ผู้ซื้อจึงข้ามไปเสนอกับผู้ถือหุ้น'),
   ('Neither partner wanted full control, so they set up a fifty-fifty ………… .',
    'joint venture',
    u'ถือคนละครึ่ง ไม่มีใครควบคุมฝ่ายเดียว'),
   ('The promised ………… never appeared, and the combined cost base actually rose.',
    'synergies',
    u'ประโยชน์จากการรวมกันที่ประมาณการไว้ แต่เกิดขึ้นจริงน้อยกว่าที่คิด'),
  ]},
]

# ── Part II · A ── ตัดสินว่าวลีนามเรียงคำถูกหรือไม่
# (วลี, เรียงถูกไหม, รูปที่ถูกถ้าผิด, คำอธิบาย)
# จำนวนข้อที่เรียงถูกในแต่ละชุดตั้งใจให้ไม่เท่ากัน คือ 3 2 4 1 3
# ถ้าเท่ากันทุกชุด เดาว่าถูกรวดก็ได้คะแนนฟรีเท่ากันหมด
P2A = [
 [('a highly confidential board report', True, '',
   u'ADVERB → ADJECTIVE → NOUN → HEAD NOUN ครบถูกลำดับ'),
  ('a cost new control system', False, 'a new cost control system',
   u'adjective ต้องอยู่หน้านามขยายทั้งหมด · new ต้องมาก่อน cost control'),
  ('an extremely detailed market survey', True, '',
   u'extremely ติดหน้า detailed แล้วตามด้วยนามขยาย market จบที่ survey'),
  ('a seriously product delayed launch', False, 'a seriously delayed product launch',
   u'adverb หลุดจาก adjective · seriously ต้องติดกับ delayed'),
  ('a newly appointed sales director', True, '',
   u'newly ขยาย appointed ซึ่งเป็น -ed participle แล้วตามด้วย sales และ director'),
 ],
 [('an increasingly market complex position', False, 'an increasingly complex market position',
   u'market ไปคั่นระหว่าง increasingly กับ complex · adverb ต้องติด adjective เสมอ'),
  ('a detailed absolutely training manual', False, 'an absolutely detailed training manual',
   u'adverb ต้องอยู่หน้า adjective ไม่ใช่หลัง · และต้องใช้ an เพราะขึ้นต้นด้วยสระ'),
  ('a quarterly sales performance review', True, '',
   u'ไม่มี adverb · adjective quarterly นำหน้านามขยาย sales performance และ head noun review'),
  ('a supplier new contract badly drafted', False, 'a badly drafted new supplier contract',
   u'คำขยายทั้งหมดต้องอยู่หน้าคำนาม ภาษาอังกฤษไม่วางไว้ข้างหลังแบบภาษาไทย'),
  ('a materially different delivery schedule', True, '',
   u'materially ขยาย different แล้วตามด้วยนามขยาย delivery จบที่ head noun schedule'),
 ],
 [('a badly damaged supplier relationship', True, '',
   u'badly ขยาย damaged แล้วตามด้วย supplier และ relationship'),
  ('a confidential highly pricing memo', False, 'a highly confidential pricing memo',
   u'adverb ต้องอยู่ติดหน้า adjective · highly ต้องมาก่อน confidential'),
  ('a three-year distribution plan', True, '',
   u'ตัวเลขกับหน่วยเวลาที่ขยายคำนาม ใช้รูปเอกพจน์และมีขีดกลาง เขียนแบบนี้ถูกแล้ว'),
  ('a very lucrative advisory contract', True, '',
   u'very ขยาย lucrative แล้วตามด้วย advisory และ contract'),
  ('a growing customer service backlog', True, '',
   u'growing เป็น -ing participle นำหน้านามขยาย customer service และ head noun backlog'),
 ],
 [('a highly aggressive pricing policy', True, '',
   u'highly ขยาย aggressive แล้วตามด้วยนามขยาย pricing และ policy'),
  ('a very perfect quality control system', False, 'an absolutely perfect quality control system',
   u'perfect เป็น adjective ที่สุดทางแล้ว ใช้กับ absolutely ไม่ใช่ very'),
  ('an extremely customer detailed survey', False, 'an extremely detailed customer survey',
   u'customer ไปคั่นระหว่าง extremely กับ detailed · adverb ต้องติด adjective เสมอ'),
  ('a report highly confidential global', False, 'a highly confidential global report',
   u'คำขยายทั้งหมดอยู่หน้าคำนาม และ adverb ต้องติดหน้า adjective'),
  ('a relations new investor department', False, 'a new investor relations department',
   u'นามขยายต้องเรียงเป็น investor relations ตามลำดับ และ adjective new อยู่หน้าสุด'),
 ],
 [('an absolutely essential safety procedure', True, '',
   u'absolutely ใช้กับ essential ได้เพราะเป็น adjective ที่สุดทางแล้ว'),
  ('a monthly highly reliable delivery service', False, 'a highly reliable monthly delivery service',
   u'เอา monthly ไปคั่นระหว่าง adverb กับ adjective ไม่ได้'),
  ('a drastically reduced marketing budget', True, '',
   u'drastically ขยาย reduced แล้วตามด้วย marketing และ budget'),
  ('a decreased waiting list that keeps getting longer', False,
   'a growing waiting list that keeps getting longer',
   u'ประโยคบอกว่ายาวขึ้นเรื่อย ๆ จึงต้องใช้ -ing ที่แปลว่ากำลังโต ไม่ใช่ -ed ที่แปลว่าถูกทำให้ลดลง'),
  ('a two-hour board meeting', True, '',
   u'two-hour เอกพจน์และมีขีดกลาง ถูกต้องแล้ว'),
 ],
]

# ── Part II · B ── เลือกรูปกริยาที่ถูกต้อง เรื่องการคาดการณ์และความน่าจะเป็น
# (ประโยค, ตัวเลือกทั้งหมดโดยตัวแรกคือคำตอบ, เหตุผล)
# ทุกประโยควางในงานที่คนทำงานบริษัทเจอจริง
P2B = [
 [('By the end of March, the team ………… the rollout in all four regions.',
   ['will have finished', 'will be finishing', 'finishes', 'is finishing'],
   u'เจอ by + เวลา ให้ใช้ future perfect เสมอ เพราะ by แปลว่าภายในก่อนถึง ซึ่งบอกว่าเสร็จแล้ว'),
  ('At nine tomorrow morning, we ………… the new designs with the client.',
   ['will be reviewing', 'will have reviewed', 'review', 'have reviewed'],
   u'at + เวลา ชี้จุดเวลาแล้วถามว่าตอนนั้นกำลังทำอะไรอยู่ จึงใช้ future continuous'),
  ('The contract was signed last week, so the terms ………… been agreed.',
   ['must have', 'can’t have', 'might not have', 'should not have'],
   u'มีหลักฐานว่าเซ็นแล้ว จึงมั่นใจสูงราว 80 เปอร์เซ็นต์ ใช้ must have'),
  ('If we ………… the new system this year, we will need extra training days.',
   ['adopt', 'will adopt', 'adopted', 'would adopt'],
   u'first conditional คือ If + V1 แล้ว will + V1 · ห้ามใส่ will ในประโยค if เด็ดขาด'),
  ('There’s ………… to be another price war in this sector next year.',
   ['certain', 'certainly', 'certainty', 'certainly going'],
   u'รูปที่ถูกคือ There’s certain to be + คำนาม · ขาด to be ไม่ได้'),
 ],
 [('By the time the project closes, we ………… every point on the client’s list.',
   ['will have cleared', 'will be clearing', 'clear', 'are clearing'],
   u'by the time + ประโยค บอกว่าเสร็จก่อนถึงจุดนั้น จึงใช้ future perfect'),
  ('This time next month, the new team ………… on the Singapore launch.',
   ['will be working', 'will have worked', 'works', 'has worked'],
   u'this time + เวลา เป็นการชี้จุดเวลาแล้วถามว่าตอนนั้นกำลังทำอะไรอยู่'),
  ('Look at the order book. That customer ………… come back at all.',
   ['isn’t going to', 'won’t be', 'wasn’t going to', 'hasn’t gone to'],
   u'มีหลักฐานตรงหน้าคือสมุดคำสั่งซื้อ จึงใช้ going to · will ใช้เมื่อเป็นความเห็นหรือตัดสินใจเดี๋ยวนั้น'),
  ('Prices are ………… to rise once the new tariff takes effect.',
   ['likely', 'probable', 'possible', 'certainly'],
   u'likely ใช้รูป be likely to ได้ ส่วน probable ใช้ได้เฉพาะ It is probable that'),
  ('They ………… received our proposal by now, I am fairly sure.',
   ['must have', 'might have', 'could have', 'would have'],
   u'must ใช้กับความมั่นใจราว 80 เปอร์เซ็นต์ · might คือราว 20 เปอร์เซ็นต์'),
 ],
 [('Next year, she ………… in the regional sales team in Singapore.',
   ['will be working', 'will have worked', 'works', 'has worked'],
   u'ปีหน้าเธอจะกำลังทำงานอยู่ที่นั่น จึงใช้ future continuous'),
  ('He is picking up his papers and standing up. I think he is ………… close the meeting.',
   ['about to', 'bound to', 'likely to', 'due to'],
   u'about to แปลว่ากำลังจะเกิดในอีกไม่กี่วินาที ซึ่งตรงกับสัญญาณที่เห็นตรงหน้า'),
  ('The parcel ………… have gone to the wrong address, but I am not sure.',
   ['may', 'must', 'will', 'can’t'],
   u'may หรือ could ใช้กับความมั่นใจราว 40 เปอร์เซ็นต์'),
  ('If you ………… the figures earlier, you would have saved the team two days.',
   ['had checked', 'checked', 'have checked', 'would check'],
   u'third conditional คือ If + had + V3 แล้ว would have + V3 · ใช้กับเรื่องที่ไม่ได้เกิดขึ้นในอดีต'),
  ('By two thousand and thirty, most firms ………… their records to the cloud.',
   ['will have moved', 'will be moving', 'move', 'are moving'],
   u'by + ปี บอกว่าเสร็จก่อนถึงปีนั้น จึงใช้ future perfect'),
 ],
 [('From the first of next month, we ………… the new travel policy to every office.',
   ['will be applying', 'will have applied', 'have applied', 'applied'],
   u'from + วันที่ แปลว่าเริ่มตั้งแต่วันนั้นแล้วทำต่อเนื่อง จึงใช้ future continuous'),
  ('She is always late with the schedules, so she is ………… miss this deadline too.',
   ['bound to', 'about to', 'unlikely to', 'due to'],
   u'bound to แปลว่าแน่นอนว่าจะ มักใช้กับสิ่งที่เกิดซ้ำจนคาดเดาได้'),
  ('It is ………… that the retirement age will be increased within ten years.',
   ['likely', 'like', 'alike', 'likeness'],
   u'It is likely that + ประโยคเต็ม · อีกสามตัวเลือกเป็นคำคนละชนิด'),
  ('Don’t call me tomorrow afternoon because I ………… on the tender all day.',
   ['will be working', 'will have worked', 'work', 'worked'],
   u'all day เป็นช่วงเวลาต่อเนื่อง จึงใช้ future continuous'),
  ('There is ………… chance of the design being approved before Friday.',
   ['no', 'not', 'none', 'nothing'],
   u'There is no chance of + V-ing · of ตามด้วย V-ing เสมอ ไม่ใช่ to'),
 ],
 [('At four this afternoon, the committee ………… the new supplier list.',
   ['will be discussing', 'will have discussed', 'discusses', 'has discussed'],
   u'at + เวลา ชี้จุดเวลา จึงใช้ future continuous'),
  ('I ………… whether the buyer will raise the offer at all.',
   ['doubt', 'doubtful', 'doubtless', 'am doubt'],
   u'I doubt whether + ประโยค เป็นการแสดงว่าไม่น่าจะเกิด'),
  ('The fund ………… two hundred million in shares by the end of the quarter.',
   ['will have bought', 'will be bought', 'will be buying', 'will have been bought'],
   u'by the end of ใช้ future perfect · ระวัง will be bought ซึ่งเป็น passive แปลว่ากองทุนถูกซื้อ ผิดความหมายทั้งประโยค'),
  ('It is ………… probable that the group will open a second plant this year.',
   ['quite', 'quiet', 'quietly', 'quit'],
   u'It is quite probable that เป็นรูปมาตรฐานของระดับน่าจะเป็น · ระวังสะกดสับสนกับ quiet'),
  ('The courier tracking shows delivered, so the parcel ………… have arrived this morning.',
   ['will', 'might', 'may', 'could'],
   u'มีหลักฐานยืนยันแล้ว จึงมั่นใจ 100 เปอร์เซ็นต์ ใช้ will'),
 ],
]
