# -*- coding: utf-8 -*-
"""ข้อสอบ Part I และ Part II ของวิชาภาษาอังกฤษ ตามแนวข้อสอบที่อาจารย์ให้มา

Part I  · Vocabulary      10 คะแนน · A ศัพท์การตลาด 5 ข้อ · B ศัพท์ M&A 5 ข้อ
          รูปแบบ เลือกวลีจากกล่องคำมาเติมให้ประโยคสมบูรณ์
Part II · Language Points 10 คะแนน · A ลำดับคำในวลีนาม 5 ข้อ · B รูปกริยาคาดการณ์ 5 ข้อ
          รูปแบบ A ตัดสินว่าวลีเรียงถูกหรือไม่ · B เลือกรูปกริยาที่ถูก

ทุกข้อ 1 คะแนน ห้าชุด ใช้คู่กับ Part III ชุดเดียวกัน รวมชุดละ 40 คะแนน
"""

# ── Part I · A ── เติมวลีศัพท์การตลาดจากกล่องคำ
# แต่ละชุดมีกล่องคำ 8 วลี แต่ใช้จริง 5 ข้อ ที่เหลือเป็นตัวลวง
P1A = [
 {'box': ['market research', 'market share', 'brand loyalty', 'product launch',
          'customer profile', 'market leader', 'brand awareness', 'price range'],
  'items': [
   ('Before we decide anything, we need to carry out ………… in all four cities.',
    'market research',
    u'ใช้ carry out คู่กับ market research เสมอ · ห้ามใช้ make'),
   ('Our ………… fell from eighteen percent to fourteen percent last year.',
    'market share',
    u'ตัวเลขเปอร์เซ็นต์ที่บริษัทครองอยู่ คือส่วนแบ่งตลาด'),
   ('The ………… was delayed by three months because of supply problems.',
    'product launch',
    u'สิ่งที่ถูกเลื่อนได้และเกี่ยวกับสินค้าใหม่ คือการเปิดตัวสินค้า'),
   ('Building up a ………… means analysing who our buyers actually are.',
    'customer profile',
    u'analysing who our buyers are คือการสร้างภาพลักษณะกลุ่มลูกค้า'),
   ('Shoppers switch brands easily here, so ………… is very low.',
    'brand loyalty',
    u'switch brands easily = ไม่ภักดีต่อแบรนด์'),
  ]},
 {'box': ['marketing mix', 'market segmentation', 'brand positioning', 'product portfolio',
          'customer retention', 'target market', 'word of mouth', 'market penetration'],
  'items': [
   ('The ………… covers product, price, place and promotion.',
    'marketing mix',
    u'สี่ P รวมกันเรียกว่าส่วนประสมการตลาด'),
   ('………… divides buyers into groups with similar needs.',
    'Market segmentation',
    u'แบ่งผู้ซื้อออกเป็นกลุ่ม คือการแบ่งส่วนตลาด'),
   ('Keeping existing buyers happy is cheaper than finding new ones, so ………… matters.',
    'customer retention',
    u'keeping existing buyers = การรักษาลูกค้าเดิม'),
   ('We now sell forty different items, which is a very wide ………… .',
    'product portfolio',
    u'ของทั้งหมดที่บริษัทขาย เรียกรวมว่ากลุ่มผลิตภัณฑ์'),
   ('The restaurant spends nothing on advertising and grew entirely through ………… .',
    'word of mouth',
    u'ไม่ลงโฆษณาแต่โตได้ คือการบอกต่อปากต่อปาก'),
  ]},
 {'box': ['market niche', 'focus group', 'special offer', 'brand extension',
          'retail outlets', 'product feature', 'market adaptation', 'sales forecast'],
  'items': [
   ('We ran six ………… sessions and recorded what people said about the packaging.',
    'focus group',
    u'เชิญคนมานั่งคุยเป็นกลุ่ม คือ focus group'),
   ('The unique selling point is the ………… that makes us different from rivals.',
    'product feature',
    u'USP คือคุณสมบัติของสินค้าที่ไม่เหมือนใคร'),
   ('The recipe is too sweet for this market, so some ………… is needed.',
    'market adaptation',
    u'ปรับสินค้าให้เข้ากับตลาดนั้น คือ market adaptation'),
   ('Our distributor supplies eight thousand ………… across the country.',
    'retail outlets',
    u'ร้านค้าที่ขายปลีก ใช้รูปพหูพจน์เพราะมีแปดพันแห่ง'),
   ('Launching shampoo under our famous soap name was a ………… .',
    'brand extension',
    u'เอาชื่อแบรนด์เดิมไปทำสินค้าประเภทใหม่ คือการต่อยอดแบรนด์'),
  ]},
 {'box': ['questionnaire', 'market sector', 'premium product', 'free samples',
          'advertising campaign', 'distributor', 'market leader', 'sales targets'],
  'items': [
   ('Two thousand shoppers completed our ………… online.',
    'questionnaire',
    u'สิ่งที่คนกรอกตอบ คือแบบสอบถาม'),
   ('They hold thirty-one percent of the market, which makes them the ………… .',
    'market leader',
    u'ครองส่วนแบ่งสูงสุด คือผู้นำตลาด · ระวังอย่าเขียน marketing leader'),
   ('We priced it above every rival, so it is clearly a ………… .',
    'premium product',
    u'ตั้งราคาสูงกว่าคู่แข่งทุกราย คือสินค้าระดับพรีเมียม'),
   ('Handing out ………… in stores is still the fastest way to get people to try it.',
    'free samples',
    u'แจกให้ลองฟรี คือ free samples'),
   ('The ………… will run on television and social media for six weeks.',
    'advertising campaign',
    u'สิ่งที่ออกอากาศเป็นช่วงเวลา คือแคมเปญโฆษณา'),
  ]},
 {'box': ['wholesaler', 'brand image', 'market survey', 'point of sale',
          'niche market', 'endorsement', 'price promotion', 'customer base'],
  'items': [
   ('After the scandal, our ………… was badly damaged and sales fell.',
    'brand image',
    u'สิ่งที่คนคิดถึงแบรนด์ เสียหายได้ คือภาพลักษณ์แบรนด์'),
   ('We have built up a loyal ………… of fifty thousand households.',
    'customer base',
    u'กลุ่มลูกค้าที่สะสมมา คือฐานลูกค้า'),
   ('We sell to a ………… , who then supplies hundreds of small shops.',
    'wholesaler',
    u'ขายส่งต่อให้ร้านเล็ก คือผู้ค้าส่ง'),
   ('A celebrity ………… can work well, but it is expensive.',
    'endorsement',
    u'ให้คนดังมารับรองสินค้า คือ endorsement'),
   ('It is small but very specific, so it is best described as a ………… .',
    'niche market',
    u'เล็กแต่เจาะจงมาก คือตลาดเฉพาะกลุ่ม'),
  ]},
]

# ── Part I · B ── เติมวลีศัพท์การควบรวมกิจการจากกล่องคำ
P1B = [
 {'box': ['made a bid', 'rejected the bid', 'took a stake', 'hostile takeover',
          'joint venture', 'due diligence', 'synergy', 'management buyout'],
  'items': [
   ('In September Kraft ………… for Cadbury worth ten point two billion pounds.',
    'made a bid',
    u'ยื่นข้อเสนอซื้อ ใช้ make a bid'),
   ('The board ………… within four days, saying it undervalued the company.',
    'rejected the bid',
    u'ปฏิเสธข้อเสนอ ใช้ reject a bid'),
   ('Because the directors refused, it became a ………… .',
    'hostile takeover',
    u'กรรมการคัดค้าน ผู้ซื้อจึงไปหาผู้ถือหุ้นตรง ๆ'),
   ('During ………… the buyer found a problem at two of the plants.',
    'due diligence',
    u'ตรวจสอบสถานะกิจการก่อนซื้อ'),
   ('The five directors borrowed money and bought the firm themselves, in a ………… .',
    'management buyout',
    u'ผู้บริหารซื้อกิจการที่ตัวเองทำงานอยู่'),
  ]},
 {'box': ['set up a joint venture', 'sold its stake', 'raised its bid', 'friendly takeover',
          'parent company', 'economies of scale', 'white knight', 'subsidiary'],
  'items': [
   ('The two firms ………… in Hungary, each taking fifty percent.',
    'set up a joint venture',
    u'ตั้งกิจการร่วมค้า ใช้ set up'),
   ('After the first refusal the bidder ………… by forty pence a share.',
    'raised its bid',
    u'เพิ่มราคาที่เสนอ ใช้ raise a bid'),
   ('Both boards agreed, so this was a ………… , not a hostile one.',
    'friendly takeover',
    u'คณะกรรมการเห็นชอบทั้งสองฝ่าย'),
   ('Pixar became a ………… of Disney after the deal completed.',
    'subsidiary',
    u'บริษัทที่ถูกอีกบริษัทควบคุม คือบริษัทย่อย'),
   ('Producing at a larger scale cuts the cost per unit, which is called ………… .',
    'economies of scale',
    u'ยิ่งผลิตมาก ต้นทุนต่อหน่วยยิ่งต่ำ'),
  ]},
 {'box': ['withdrew its bid', 'built up a stake', 'competition authority', 'merged with',
          'share price', 'shareholders', 'premium', 'asset stripping'],
  'items': [
   ('A rival had quietly ………… of five percent before anyone noticed.',
    'built up a stake',
    u'ทยอยสะสมหุ้น ใช้ build up a stake'),
   ('The ………… in Brussels opened a full investigation into the deal.',
    'competition authority',
    u'หน่วยงานกำกับการแข่งขัน'),
   ('In July the buyer ………… and walked away from the deal.',
    'withdrew its bid',
    u'ถอนข้อเสนอ ใช้ withdraw a bid'),
   ('They paid a twenty-five percent ………… over the market value of the shares.',
    'premium',
    u'ส่วนเพิ่มเหนือราคาตลาด'),
   ('Exxon ………… Mobil in nineteen ninety-nine to form a single company.',
    'merged with',
    u'ควบรวมกับ ใช้ merge with'),
  ]},
 {'box': ['acquired', 'target', 'bidder', 'divest',
          'spin-off', 'vendor finance', 'poison pill', 'stake'],
  'items': [
   ('Disney ………… Pixar for seven point four billion dollars in two thousand and six.',
    'acquired',
    u'ซื้อกิจการ ใช้ acquire a company'),
   ('The company being bought is usually called the ………… .',
    'target',
    u'บริษัทเป้าหมาย'),
   ('The seller left part of the price in the business, which is known as ………… .',
    'vendor finance',
    u'ผู้ขายให้ผู้ซื้อกู้ส่วนหนึ่งของราคา'),
   ('The group plans to ………… two loss-making divisions next year.',
    'divest',
    u'ขายกิจการทิ้ง ตรงข้ามกับ acquire'),
   ('Separating the software unit into an independent company was a ………… .',
    'spin-off',
    u'แยกหน่วยธุรกิจออกมาตั้งเป็นบริษัทใหม่'),
  ]},
 {'box': ['holds a stake', 'accepted the bid', 'merger of equals', 'takeover',
          'antitrust', 'due diligence', 'sell its stake', 'shareholder'],
  'items': [
   ('The founding family still ………… of twelve percent in the business.',
    'holds a stake',
    u'ถือหุ้นอยู่ ใช้ hold a stake'),
   ('Shareholders voted and ………… at the higher price.',
    'accepted the bid',
    u'ตอบรับข้อเสนอ ใช้ accept a bid'),
   ('When two companies of similar size combine, it is described as a ………… .',
    'merger of equals',
    u'ควบรวมโดยที่ทั้งคู่ฐานะเท่ากัน'),
   ('Getting control by buying over half the shares is a ………… .',
    'takeover',
    u'ซื้อหุ้นเกินครึ่งเพื่อคุมอำนาจ · ตรงนี้ต้องการคำนาม จึงเขียนติดกัน'),
   ('The fund decided to ………… and take the profit.',
    'sell its stake',
    u'ขายหุ้นที่ถืออยู่ ใช้ sell a stake'),
  ]},
]

# ── Part II · A ── ตัดสินว่าวลีนามเรียงลำดับถูกหรือไม่
# (วลีที่เห็น, ถูกไหม, วลีที่ถูก, เหตุผล)
P2A = [
 [('a really impressive advertising campaign', True, '',
   u'ADVERB → ADJECTIVE → NOUN → HEAD NOUN ครบถูกลำดับ'),
  ('a customer new relations department', False, 'a new customer relations department',
   u'adjective ต้องอยู่หน้านามขยายทั้งหมด · new ต้องมาก่อน customer relations'),
  ('a highly competitive mobile phone market', True, '',
   u'highly ติดหน้า competitive แล้วตามด้วยนามขยาย mobile phone จบที่ market'),
  ('an incredibly product successful launch', False, 'an incredibly successful product launch',
   u'adverb หลุดจาก adjective · incredibly ต้องติดกับ successful'),
  ('a loyal customer base', True, '',
   u'ไม่มี adverb · adjective loyal นำหน้านามขยาย customer และ head noun base'),
 ],
 [('an extremely thorough sales report', True, '',
   u'extremely ขยาย thorough แล้วตามด้วย sales และ report'),
  ('a brilliant absolutely global campaign', False, 'an absolutely brilliant global campaign',
   u'adverb ต้องอยู่หน้า adjective ไม่ใช่หลัง · และต้องใช้ an เพราะขึ้นต้นด้วยสระ'),
  ('an increasingly competitive marketing environment', True, '',
   u'increasingly ขยาย competitive แล้วตามด้วย marketing และ environment'),
  ('a marketing new budget drastically reduced', False, 'a drastically reduced marketing budget',
   u'คำขยายทั้งหมดต้องอยู่หน้าคำนาม ภาษาอังกฤษไม่วางไว้ข้างหลังแบบภาษาไทย'),
  ('a rapidly product expanding portfolio', False, 'a rapidly expanding product portfolio',
   u'เอา product ไปคั่นระหว่าง adverb กับ participle ไม่ได้ · rapidly ต้องติด expanding'),
 ],
 [('a badly damaged brand image', True, '',
   u'badly ขยาย damaged แล้วตามด้วย brand และ image'),
  ('a confidential highly sales report', False, 'a highly confidential sales report',
   u'adverb ต้องอยู่ติดหน้า adjective · highly ต้องมาก่อน confidential'),
  ('a very lucrative sponsorship deal', True, '',
   u'very ขยาย lucrative แล้วตามด้วย sponsorship และ deal'),
  ('a three-year expansion programme', True, '',
   u'ตัวเลขกับหน่วยเวลาที่ขยายคำนาม ใช้รูปเอกพจน์และมีขีดกลาง เขียนแบบนี้ถูกแล้ว'),
  ('a shrinking customer base', True, '',
   u'ไม่มี adverb · shrinking เป็น -ing participle นำหน้านามขยายและ head noun'),
 ],
 [('a highly aggressive pricing strategy', True, '',
   u'highly ขยาย aggressive แล้วตามด้วย pricing และ strategy'),
  ('a very brilliant marketing plan', False, 'an absolutely brilliant marketing plan',
   u'brilliant เป็น adjective ที่สุดทางแล้ว ใช้กับ absolutely ไม่ใช่ very'),
  ('an extremely market detailed segmentation', False, 'an extremely detailed market segmentation',
   u'market ไปคั่นระหว่าง extremely กับ detailed · adverb ต้องติด adjective เสมอ'),
  ('a campaign highly successful global', False, 'a highly successful global campaign',
   u'คำขยายทั้งหมดอยู่หน้าคำนาม และ adverb ต้องติดหน้า adjective'),
  ('a relations new customer department', False, 'a new customer relations department',
   u'นามขยายต้องเรียงเป็น customer relations ตามลำดับ และ adjective new อยู่หน้าสุด'),
 ],
 [('an absolutely brilliant global campaign', True, '',
   u'absolutely ใช้กับ brilliant ได้เพราะเป็น adjective ที่สุดทางแล้ว'),
  ('a mobile highly competitive phone market', False, 'a highly competitive mobile phone market',
   u'เอา mobile ไปคั่นระหว่าง adverb กับ adjective ไม่ได้'),
  ('a drastically reduced marketing budget', True, '',
   u'drastically ขยาย reduced แล้วตามด้วย marketing และ budget'),
  ('an expanded customer base that grows every month', False,
   'an expanding customer base that grows every month',
   u'ประโยคบอกว่ากำลังโตอยู่ จึงต้องใช้ -ing ไม่ใช่ -ed'),
  ('a two-hour board meeting', True, '',
   u'two-hour เอกพจน์และมีขีดกลาง ถูกต้องแล้ว'),
 ],
]

# ── Part II · B ── เลือกรูปกริยาที่ถูกต้อง เรื่องการคาดการณ์และความน่าจะเป็น
# (ประโยค, ตัวเลือกทั้งหมดโดยตัวแรกคือคำตอบ, เหตุผล)
P2B = [
 [('By December, we ………… back the whole loan.',
   ['will have paid', 'will be paying', 'will pay', 'are paying'],
   u'by + เวลา บอกว่าเสร็จก่อนถึงจุดนั้น จึงใช้ future perfect'),
  ('This time next year, we ………… the results of the merger.',
   ['will be enjoying', 'will have enjoyed', 'enjoy', 'have enjoyed'],
   u'this time + เวลา ชี้จุดเวลาแล้วถามว่าตอนนั้นกำลังทำอะไร จึงใช้ future continuous'),
  ('Their plane landed five minutes ago. They ………… arrived yet.',
   ["can't have", "mustn't have", "shouldn't have", "wouldn't have"],
   u'รูปปฏิเสธของ must ในความหมายคาดเดา คือ can’t เท่านั้น · mustn’t แปลว่าห้าม'),
  ('If we ………… the Chinese market, we will need a local partner.',
   ['enter', 'will enter', 'entered', 'will have entered'],
   u'first conditional ห้ามใส่ will ในประโยค if'),
  ("There's ………… to be more acquisitions in this sector next year.",
   ['certain', 'certainly', 'certainty', 'certained'],
   u'รูปที่ถูกคือ There’s certain to be + คำนาม'),
 ],
 [('We ………… a special discount from January the first.',
   ['will be offering', 'will have offered', 'have offered', 'offered'],
   u'from + วันที่ แปลว่าเริ่มแล้วทำต่อเนื่อง จึงใช้ future continuous'),
  ("Don't phone me tomorrow because I ………… on the bid all morning.",
   ["will be working", 'will have worked', 'work', 'worked'],
   u'all morning เป็นช่วงเวลาต่อเนื่อง จึงใช้ future continuous'),
  ('There is ………… chance of the merger taking place.',
   ['no', 'not', 'none', 'any'],
   u'รูปที่ถูกคือ There’s no chance of + V-ing'),
  ('It is unlikely ………… the retirement age will be increased to seventy-five.',
   ['that', 'to', 'for', 'of'],
   u'It is unlikely that + ประโยคเต็ม · ส่วน be unlikely to ใช้เมื่อประธานอยู่ข้างหน้า'),
  ('Look at that queue. We ………… miss our flight.',
   ['are going to', 'will', 'would', 'are about'],
   u'มีหลักฐานตรงหน้าคือคิวยาว จึงใช้ going to'),
 ],
 [('By the end of next year, we ………… six new products in three years.',
   ['will have launched', 'will be launching', 'launch', 'are launching'],
   u'by the end of เป็นการนับผลงานสะสม จึงใช้ future perfect'),
  ('I ………… here for three years next May.',
   ['will have been', 'will be being', 'am being', 'will be'],
   u'นับระยะเวลาสะสมถึงจุดหนึ่งในอนาคต จึงใช้ future perfect'),
  ("She's ………… be late, she always is.",
   ['bound to', 'about to', 'unlikely to', 'due for'],
   u'bound to แปลว่าแน่นอนว่าจะ ใช้กับสิ่งที่เกิดซ้ำจนคาดเดาได้'),
  ('Prices are ………… to rise next quarter.',
   ['likely', 'probable', 'possible', 'certainly'],
   u'likely ใช้รูป be likely to ได้ ส่วน probable ใช้ได้เฉพาะ It is probable that'),
  ('They ………… have received our offer by now, I am fairly sure.',
   ['must', 'might', 'could', 'would'],
   u'must ใช้กับความมั่นใจราว 80% · might คือ 20%'),
 ],
 [('Next year, she ………… in our Tokyo office.',
   ['will be working', 'will have worked', 'works', 'has worked'],
   u'ปีหน้าเธอจะกำลังทำงานอยู่ที่นั่น จึงใช้ future continuous'),
  ("He's tapping his glass. I think he's ………… make a speech.",
   ['about to', 'bound to', 'likely to', 'due to'],
   u'about to แปลว่ากำลังจะเกิดในอีกไม่กี่วินาที'),
  ('The email ………… have gone into her spam folder, but I am not sure.',
   ['may', 'must', 'will', "can't"],
   u'may หรือ could ใช้กับความมั่นใจราว 40%'),
  ('If you ………… harder, you would be able to do it.',
   ['tried', 'try', 'will try', 'would try'],
   u'second conditional คือ If + ช่องสอง แล้ว would + ช่องหนึ่ง'),
  ('By twenty fifty, most banks ………… half of their branches.',
   ['will have closed', 'will be closing', 'close', 'are closing'],
   u'by + ปี บอกว่าเสร็จก่อนถึงปีนั้น จึงใช้ future perfect'),
 ],
 [('At nine on Monday, the new CEO ………… the whole department.',
   ['will be meeting', 'will have met', 'meets', 'has met'],
   u'at + เวลา ชี้จุดเวลา จึงใช้ future continuous'),
  ('I ………… whether L’Oréal will make a bid at all.',
   ['doubt', 'doubtful', 'doubtless', 'am doubt'],
   u'I doubt whether + ประโยค เป็นการแสดงว่าไม่น่าจะเกิด'),
  ('The Bank of England ………… one hundred billion in bonds by the end of July.',
   ['will have bought', 'will be bought', 'will be buying', 'will have been bought'],
   u'by the end of ใช้ future perfect · ระวัง will be bought เป็น passive แปลว่าธนาคารถูกซื้อ'),
  ('It is ………… probable that an economic upturn will start next year.',
   ['quite', 'quiet', 'quietly', 'quit'],
   u'It’s quite probable that เป็นรูปมาตรฐานของระดับน่าจะเป็น'),
  ('The parcel ………… have arrived this morning, I am certain of it.',
   ['will', 'might', 'may', 'could'],
   u'will ใช้กับความมั่นใจ 100%'),
 ],
]
