# -*- coding: utf-8 -*-
u"""ข้อสอบ Part I และ Part II ชุดที่ 6 ถึง 15 · แบบฝึกเพิ่มเติม

ชุดที่ 1 ถึง 5 อยู่ใน tools/exam-data.py และจับคู่กับ Part III ที่มีไฟล์เสียง
ส่วนสิบชุดในไฟล์นี้เป็นแบบฝึกล้วน ไม่มี Part III จึงไม่มีปุ่มข้ามไปฝึกฟัง
แยกไฟล์ไว้เพราะรวมกันแล้วยาวเกินกว่าจะหาที่จะแก้เจอ

กติกาเดียวกับชุดแรกทุกข้อ
  Part I  กล่องคำ 8 วลี ใช้จริง 5 ข้อ อีกสามวลีเป็นตัวลวง คำตอบห้ามซ้ำกันในชุดเดียว
  Part II A จำนวนข้อที่เรียงถูกในแต่ละชุดต้องไม่เท่ากัน ไม่งั้นเดาว่าถูกรวดก็ได้คะแนนฟรี
            สิบชุดนี้ไล่เป็น 2 4 3 1 4 2 3 1 4 2 ต่อจากห้าชุดแรกที่เป็น 3 2 4 1 3
  Part II B สี่ตัวเลือก ห้ามซ้ำ ตัวแรกในลิสต์คือคำตอบ
  ไม่ใช้ชื่อบริษัทจริงหรือดีลจริง และคุมความยาวประโยคไว้ราว 12 ถึง 22 คำ

บริบทของทุกข้อยังเป็นงานที่นิสิตบัญชีปีสามเจอจริง คือ งบประมาณ ต้นทุน
การตัดยอดตามงวด การตีมูลค่า การสอบทาน และการจัดทำงบการเงินรวม
"""

# ── Part I · A ── เติมวลีศัพท์การตลาดจากกล่องคำ · ชุดที่ 6 ถึง 15
P1A = [
 # ชุดที่ 6
 {'box': ['sales forecast', 'distribution channel', 'after-sales service', 'point of sale',
          'mass market', 'trade fair', 'unique selling point', 'loss leader'],
  'items': [
   ('The ………… for the fourth quarter was built on last year’s figures plus four percent.',
    'sales forecast',
    u'ประมาณการยอดขาย เป็นตัวเลขที่สร้างจากข้อมูลในอดีตแล้วบวกอัตราการเติบโต'),
   ('Goods reach the buyer through a single ………… , so one delay stops everything.',
    'distribution channel',
    u'เส้นทางที่สินค้าเดินจากผู้ผลิตไปถึงผู้ซื้อ · มีช่องทางเดียวจึงเสี่ยงสูง'),
   ('The warranty provision covers ………… for three years after the sale.',
    'after-sales service',
    u'บริการหลังการขาย เป็นภาระที่ต้องตั้งประมาณการหนี้สินไว้ล่วงหน้า'),
   ('Stock is counted at the ………… , which is why the till records matter to the audit.',
    'point of sale',
    u'จุดที่เกิดการขายจริง · ข้อมูลจากเครื่องบันทึกเงินสดตรงนี้คือหลักฐานของผู้สอบบัญชี'),
   ('The bread is sold below cost as a ………… to bring shoppers into the store.',
    'loss leader',
    u'สินค้าที่ยอมขายขาดทุนเพื่อดึงคนเข้าร้าน แล้วไปทำกำไรจากสินค้าตัวอื่น'),
  ]},
 # ชุดที่ 7
 {'box': ['market value', 'customer base', 'promotional offer', 'sales representative',
          'press release', 'market entry', 'wholesaler', 'brand name'],
  'items': [
   ('The building was revalued and is now carried at its ………… rather than at cost.',
    'market value',
    u'มูลค่าตลาด · เป็นฐานการวัดมูลค่าที่ต่างจากราคาทุนเดิม'),
   ('We inherited a ………… of nine thousand accounts when we bought the smaller firm.',
    'customer base',
    u'ฐานลูกค้าทั้งหมดที่กิจการมีอยู่ · ได้ติดมากับการซื้อกิจการ'),
   ('The “three for two” ………… ran all July and cut the gross margin by two points.',
    'promotional offer',
    u'ข้อเสนอส่งเสริมการขายที่มีกำหนดเวลา · กระทบอัตรากำไรขั้นต้นโดยตรง'),
   ('Each ………… earns commission, so the accrual has to be calculated every month.',
    'sales representative',
    u'พนักงานขายที่ได้ค่านายหน้า · ต้องตั้งค่าใช้จ่ายค้างจ่ายทุกเดือน'),
   ('The ………… was issued an hour after the market closed.',
    'press release',
    u'เอกสารแถลงข่าวที่กิจการออกสู่สาธารณะ · มักออกหลังตลาดปิดเพื่อให้ทุกคนได้ข่าวพร้อมกัน'),
  ]},
 # ชุดที่ 8
 {'box': ['market niche', 'customer satisfaction', 'price list', 'advertising agency',
          'product development', 'launch date', 'market segment', 'sales channel'],
  'items': [
   ('We serve a small ………… that the large producers have never thought worth entering.',
    'market niche',
    u'ตลาดเฉพาะกลุ่มที่เล็กเกินกว่ารายใหญ่จะสนใจ'),
   ('The ………… survey scored us at eighty-two percent, up four points on last year.',
    'customer satisfaction',
    u'ความพึงพอใจของลูกค้า · วัดออกมาเป็นคะแนนแล้วเทียบกับปีก่อนได้'),
   ('Send the buyer the current ………… ; the one on the website is two years out of date.',
    'price list',
    u'รายการราคาสินค้าอย่างเป็นทางการ · ต้องใช้ฉบับล่าสุดเสมอ'),
   ('An outside ………… wrote the campaign, and their invoice is still unpaid at the year end.',
    'advertising agency',
    u'เอเจนซีโฆษณาที่รับจ้างทำแคมเปญ · ค่าบริการที่ยังไม่จ่ายต้องตั้งเป็นเจ้าหนี้'),
   ('Costs incurred during ………… can only be capitalised once the technical work is proven.',
    'product development',
    u'ขั้นพัฒนาผลิตภัณฑ์ · ต้นทุนจะบันทึกเป็นสินทรัพย์ได้ก็ต่อเมื่อพิสูจน์ความเป็นไปได้แล้ว'),
  ]},
 # ชุดที่ 9
 {'box': ['brand awareness', 'market penetration', 'premium product', 'special offer',
          'sales volume', 'target market', 'free samples', 'market sector'],
  'items': [
   ('Only one shopper in five could name us, so ………… is the first thing to fix.',
    'brand awareness',
    u'การที่ผู้บริโภครู้จักแบรนด์ · วัดจากสัดส่วนคนที่นึกชื่อออก'),
   ('We already sell there but hold two percent of it, so ………… is still very low.',
    'market penetration',
    u'ระดับการเจาะตลาด · เข้าไปแล้วแต่ยังครองส่วนแบ่งน้อยมาก'),
   ('At four times the price of the ordinary line, this is clearly a ………… .',
    'premium product',
    u'สินค้าระดับบนที่ตั้งราคาสูงกว่าสินค้าทั่วไปมาก'),
   ('The ………… ends on Sunday, after which the price returns to normal.',
    'special offer',
    u'ข้อเสนอพิเศษที่มีวันสิ้นสุดชัดเจน'),
   ('………… rose eleven percent, but revenue fell because the average price dropped.',
    'Sales volume',
    u'ปริมาณที่ขายได้ ไม่ใช่มูลค่า · ขายได้มากขึ้นแต่รายได้ลดลงได้ถ้าราคาต่อหน่วยตก'),
  ]},
 # ชุดที่ 10
 {'box': ['market segment', 'brand positioning', 'questionnaire', 'discount structure',
          'focus group', 'sales channel', 'customer profile', 'product feature'],
  'items': [
   ('The over-sixties ………… now accounts for a third of our revenue.',
    'market segment',
    u'ส่วนตลาดกลุ่มหนึ่งที่แบ่งตามลักษณะของผู้ซื้อ เช่น ช่วงอายุ'),
   ('Our ………… places us between the cheap imports and the luxury names.',
    'brand positioning',
    u'ตำแหน่งของแบรนด์ในใจผู้บริโภคเทียบกับคู่แข่ง'),
   ('The ………… gives ten percent off orders above five hundred units.',
    'discount structure',
    u'โครงสร้างส่วนลดที่ผูกกับปริมาณการสั่งซื้อ'),
   ('Online selling has become our fastest growing ………… .',
    'sales channel',
    u'ช่องทางการขายหนึ่ง ๆ เช่น หน้าร้าน ตัวแทน หรือออนไลน์'),
   ('A twelve-person ………… was asked to compare our packaging with the competitor’s.',
    'focus group',
    u'กลุ่มตัวอย่างที่เชิญมานั่งคุยและให้ความเห็นร่วมกัน'),
  ]},
 # ชุดที่ 11
 {'box': ['product lifecycle', 'marketing budget', 'market share', 'brand loyalty',
          'retail price', 'sales targets', 'market research', 'customer retention'],
  'items': [
   ('The machine is written off over five years, which matches the ………… of the product it makes.',
    'product lifecycle',
    u'วงจรชีวิตผลิตภัณฑ์ ตั้งแต่เปิดตัวจนเลิกขาย · ใช้เทียบกับอายุการให้ประโยชน์ของสินทรัพย์'),
   ('The ………… was cut in half, and the effect on volume showed up within two months.',
    'marketing budget',
    u'งบการตลาดทั้งก้อน กว้างกว่า advertising budget ซึ่งเป็นแค่ส่วนโฆษณา'),
   ('The ………… printed on the box includes value added tax.',
    'retail price',
    u'ราคาขายปลีกที่ผู้บริโภคจ่ายจริง ซึ่งรวมภาษีมูลค่าเพิ่มไว้แล้ว'),
   ('Ninety percent of our buyers came back this year, which is unusually strong ………… .',
    'brand loyalty',
    u'ความภักดีต่อแบรนด์ วัดจากสัดส่วนคนที่กลับมาซื้อซ้ำ'),
   ('No ………… had been carried out before the board committed to the new country.',
    'market research',
    u'การวิจัยตลาด ใช้คู่กับ carry out หรือ conduct · ห้ามใช้ make'),
  ]},
 # ชุดที่ 12
 {'box': ['marketing mix', 'product range', 'advertising campaign', 'market leader',
          'word of mouth', 'brand image', 'price war', 'customer service'],
  'items': [
   ('Three suppliers cut their prices in the same week, and a ………… followed.',
    'price war',
    u'สงครามราคา · ทุกรายลดราคาไล่กันจนกำไรหายทั้งอุตสาหกรรม'),
   ('Complaints are handled by a ………… team of six, whose cost sits in administrative expenses.',
    'customer service',
    u'งานบริการลูกค้า · ต้นทุนส่วนนี้อยู่ในค่าใช้จ่ายในการบริหาร ไม่ใช่ต้นทุนขาย'),
   ('Our ………… never recovered after the recall, even though the product was safe.',
    'brand image',
    u'ภาพลักษณ์ของแบรนด์ เสียได้แม้ตัวสินค้าจะไม่มีปัญหาจริง'),
   ('They have held the top position for eleven years and remain the ………… .',
    'market leader',
    u'ผู้นำตลาด คือรายที่ครองส่วนแบ่งสูงสุด · ระวังอย่าเขียน marketing leader'),
   ('The ………… cost nine million and ran across television and radio.',
    'advertising campaign',
    u'แคมเปญโฆษณาที่มีงบและระยะเวลาชัดเจน'),
  ]},
 # ชุดที่ 13
 {'box': ['market conditions', 'unique selling point', 'trade fair', 'wholesaler',
          'launch date', 'sales figures', 'market entry', 'brand extension'],
  'items': [
   ('The ………… has been moved to January so that the campaign starts after the holidays.',
    'launch date',
    u'วันเปิดตัวสินค้า เลื่อนได้และกระทบแผนการตลาดทั้งแผน'),
   ('Our ………… is the only guarantee in the industry that lasts ten years.',
    'unique selling point',
    u'จุดขายที่ไม่มีใครเหมือน · ย่อว่า USP'),
   ('We met four new buyers at the ………… in Frankfurt last March.',
    'trade fair',
    u'งานแสดงสินค้าที่ผู้ผลิตกับผู้ซื้อมาพบกัน'),
   ('A single ………… buys the whole output and resells it to hundreds of small shops.',
    'wholesaler',
    u'ผู้ค้าส่ง ซื้อยกล็อตแล้วกระจายต่อให้ร้านย่อย · ต่างจาก retailer ที่ขายถึงผู้บริโภค'),
   ('The ………… for the half year were released to the market on Thursday.',
    'sales figures',
    u'ตัวเลขยอดขายที่เปิดเผยต่อสาธารณะ · ใช้รูปพหูพจน์เสมอ'),
  ]},
 # ชุดที่ 14
 {'box': ['target market', 'market adaptation', 'questionnaire', 'free samples',
          'customer profile', 'pricing policy', 'sales channel', 'market share'],
  'items': [
   ('Our ………… is students between eighteen and twenty-four living away from home.',
    'target market',
    u'กลุ่มตลาดเป้าหมายที่กิจการตั้งใจขายให้'),
   ('The ………… sets a floor of twenty percent above direct cost on every order.',
    'pricing policy',
    u'นโยบายการตั้งราคา · ผูกกับต้นทุนทางตรงโดยตรง'),
   ('Two hundred thousand ………… were given away, and the cost went straight to expenses.',
    'free samples',
    u'สินค้าตัวอย่างที่แจกฟรี · บันทึกเป็นค่าใช้จ่ายทันที ไม่ใช่สินค้าคงเหลือ'),
   ('The label had to be rewritten in three languages, which is normal ………… .',
    'market adaptation',
    u'การปรับสินค้าให้เข้ากับตลาดปลายทาง เช่น ฉลาก รสชาติ หรือขนาดบรรจุ'),
   ('Only nine percent returned the ………… , so the results were not reliable.',
    'questionnaire',
    u'แบบสอบถาม · อัตราตอบกลับต่ำทำให้ผลไม่น่าเชื่อถือ'),
  ]},
 # ชุดที่ 15
 {'box': ['market value', 'sales targets', 'customer retention', 'product feature',
          'distribution channel', 'brand name', 'focus group', 'marketing strategy'],
  'items': [
   ('Every region beat its ………… this year, so the bonus accrual doubled.',
    'sales targets',
    u'เป้ายอดขายที่ผูกกับโบนัส · ทำได้เกินเป้าจึงต้องตั้งค่าใช้จ่ายโบนัสเพิ่ม'),
   ('The ………… alone was valued at sixty million, separately from the factories.',
    'brand name',
    u'ชื่อแบรนด์ที่ตีมูลค่าแยกจากสินทรัพย์ที่มีตัวตนได้'),
   ('Keeping an existing account costs far less, so ………… is now a board-level measure.',
    'customer retention',
    u'การรักษาลูกค้าเดิม ถูกกว่าการหาลูกค้าใหม่มาก'),
   ('The one ………… buyers mention most is that the lid can be opened with one hand.',
    'product feature',
    u'คุณสมบัติของตัวสินค้า · ถ้าไม่มีใครลอกได้ก็กลายเป็น unique selling point'),
   ('The five-year ………… was approved in March and reviewed every quarter since.',
    'marketing strategy',
    u'กลยุทธ์การตลาดระดับแผนหลัก ที่ทุกฝ่ายต้องเดินตาม'),
  ]},
]

# ── Part I · B ── เติมวลีศัพท์การควบรวมและซื้อกิจการจากกล่องคำ · ชุดที่ 6 ถึง 15
P1B = [
 # ชุดที่ 6
 {'box': ['controlling interest', 'minority interest', 'share swap', 'cash offer',
          'integration', 'regulatory approval', 'target company', 'valuation'],
  'items': [
   ('The buyer now holds fifty-two percent and therefore has a ………… .',
    'controlling interest',
    u'สัดส่วนที่เกินครึ่งจนควบคุมกิจการได้ · เป็นจุดที่ต้องเริ่มทำงบการเงินรวม'),
   ('No money changed hands; shareholders received new shares in a ………… .',
    'share swap',
    u'แลกหุ้นกับหุ้น ไม่ได้จ่ายเป็นเงินสด'),
   ('The deal could not close until ………… was granted by the competition authority.',
    'regulatory approval',
    u'การอนุมัติจากหน่วยงานกำกับดูแล เช่น หน่วยงานด้านการแข่งขันทางการค้า'),
   ('The remaining forty-nine percent is shown in the group accounts as a ………… .',
    'minority interest',
    u'ส่วนได้เสียที่ไม่มีอำนาจควบคุม · แสดงแยกในส่วนของเจ้าของในงบการเงินรวม'),
   ('The ………… took eighteen months, and the two finance systems were only merged last June.',
    'integration',
    u'การรวมระบบและทีมงานหลังปิดดีล มักใช้เวลานานกว่าที่วางแผนไว้'),
  ]},
 # ชุดที่ 7
 {'box': ['letter of intent', 'confidentiality agreement', 'bidding war', 'earn-out',
          'net assets', 'book value', 'disposal', 'holding company'],
  'items': [
   ('Before any figures were shared, both sides signed a ………… .',
    'confidentiality agreement',
    u'ข้อตกลงรักษาความลับ ต้องเซ็นก่อนเปิดข้อมูลทางการเงินให้อีกฝ่ายดู'),
   ('The parties signed a ………… in April setting out the main terms, though it was not binding.',
    'letter of intent',
    u'หนังสือแสดงเจตจำนง วางกรอบข้อตกลงไว้ก่อน แต่ยังไม่ผูกพันทางกฎหมาย'),
   ('A third bidder joined and the price rose forty percent in a ………… .',
    'bidding war',
    u'การแย่งกันเสนอราคาจนราคาถูกดันขึ้นไปสูงเกินมูลค่าพื้นฐาน'),
   ('Half the price is payable in three years only if profits hold up, which is an ………… .',
    'earn-out',
    u'ส่วนของราคาที่จ่ายภายหลังและขึ้นกับผลประกอบการที่เกิดขึ้นจริง'),
   ('The shares were sold at less than their ………… , so a loss was recognised.',
    'book value',
    u'มูลค่าตามบัญชี · ขายต่ำกว่านี้จึงเกิดผลขาดทุนจากการจำหน่าย'),
  ]},
 # ชุดที่ 8
 {'box': ['spin-off', 'leveraged buyout', 'restructuring', 'redundancies',
          'predator', 'poison pill', 'break-up fee', 'conglomerate'],
  'items': [
   ('The research division was floated separately in a ………… , and shareholders kept both holdings.',
    'spin-off',
    u'แยกหน่วยธุรกิจออกไปตั้งเป็นบริษัทใหม่ โดยผู้ถือหุ้นเดิมยังถือทั้งสองบริษัท'),
   ('Almost all of the purchase price was borrowed, which made it a ………… .',
    'leveraged buyout',
    u'ซื้อกิจการโดยใช้เงินกู้เป็นหลัก · ภาระหนี้จะไปตกอยู่กับกิจการที่ถูกซื้อ'),
   ('Four hundred ………… were announced, and the provision was recognised in the same year.',
    'redundancies',
    u'การเลิกจ้างเพราะตำแหน่งซ้ำซ้อนหลังรวมกิจการ · ต้องตั้งประมาณการหนี้สินทันที'),
   ('The board issued cheap shares to existing holders as a ………… to make the bid too expensive.',
    'poison pill',
    u'มาตรการต้านการครอบงำ ทำให้ผู้ซื้อต้องจ่ายแพงขึ้นจนไม่คุ้ม'),
   ('If either side walks away without cause, a ………… of ten million is payable.',
    'break-up fee',
    u'ค่าปรับเมื่อฝ่ายใดฝ่ายหนึ่งถอนตัวจากดีลโดยไม่มีเหตุอันควร'),
  ]},
 # ชุดที่ 9
 {'box': ['fair value', 'goodwill', 'consolidation', 'acquisition date',
          'due diligence', 'escrow', 'warranty', 'disposal'],
  'items': [
   ('Each asset acquired is measured at its ………… , not at the seller’s carrying amount.',
    'fair value',
    u'มูลค่ายุติธรรม ณ วันซื้อ · ไม่ใช่ราคาตามบัญชีเดิมของผู้ขาย'),
   ('Results are included in the group accounts from the ………… onwards.',
    'acquisition date',
    u'วันที่ผู้ซื้อได้อำนาจควบคุม · เป็นจุดเริ่มนำผลประกอบการมารวม'),
   ('Ten percent of the price sits in ………… for a year in case claims arise.',
    'escrow',
    u'เงินที่ฝากไว้กับคนกลางจนกว่าจะพ้นระยะเวลาที่อาจมีข้อเรียกร้อง'),
   ('The seller gave a ………… that no tax assessments were outstanding.',
    'warranty',
    u'คำรับรองของผู้ขายในสัญญา · ถ้าไม่จริงผู้ซื้อเรียกค่าเสียหายได้'),
   ('The ………… review picked up a pension deficit that the seller had not mentioned.',
    'due diligence',
    u'การตรวจสอบสถานะกิจการก่อนซื้อ เป็นงานที่ผู้สอบบัญชีเข้าไปทำจริง'),
  ]},
 # ชุดที่ 10
 {'box': ['bidder', 'offer price', 'shareholder approval', 'hostile',
          'friendly', 'divested', 'subsidiary', 'merger'],
  'items': [
   ('A second ………… appeared two days before the deadline.',
    'bidder',
    u'ผู้ยื่นข้อเสนอซื้อ · เป็นคำนามที่นับได้ จึงใช้กับ a ได้'),
   ('The ………… was raised twice, from nine pounds a share to eleven.',
    'offer price',
    u'ราคาที่ผู้ซื้อเสนอต่อหุ้น ปรับขึ้นได้ระหว่างการเจรจา'),
   ('Nothing can proceed without ………… at the meeting in October.',
    'shareholder approval',
    u'มติอนุมัติจากที่ประชุมผู้ถือหุ้น ไม่ใช่จากฝ่ายบริหาร'),
   ('The group ………… its Spanish operations and used the cash to repay debt.',
    'divested',
    u'ขายธุรกิจบางส่วนออกไป · เป็นกริยาในอดีตจึงลงท้าย -ed'),
   ('Because both boards were content, the press described it as a ………… of equals.',
    'merger',
    u'การควบรวมระหว่างกิจการที่มีฐานะใกล้เคียงกัน'),
  ]},
 # ชุดที่ 11
 {'box': ['takeover bid', 'white knight', 'asset stripping', 'management buyout',
          'joint venture', 'synergies', 'valuation', 'stake'],
  'items': [
   ('The ………… lapsed when only thirty percent of holders accepted.',
    'takeover bid',
    u'ข้อเสนอซื้อกิจการที่ตกไปเพราะผู้ถือหุ้นตอบรับไม่ถึงเกณฑ์'),
   ('A friendlier buyer was found, and the board treated that company as a ………… .',
    'white knight',
    u'ผู้ซื้อที่เข้ามาช่วยกิจการเป้าหมายให้พ้นจากข้อเสนอที่ไม่ต้องการ'),
   ('The factories were sold within eight months, which the unions called ………… .',
    'asset stripping',
    u'ซื้อมาแล้วแยกขายสินทรัพย์เอากำไร ไม่ได้ตั้งใจดำเนินกิจการต่อ'),
   ('The existing directors raised the finance themselves in a ………… .',
    'management buyout',
    u'ผู้บริหารเดิมหาเงินมาซื้อกิจการที่ตนบริหารอยู่'),
   ('The promised ………… of thirty million a year never showed up in the numbers.',
    'synergies',
    u'ประโยชน์จากการรวมกัน ซึ่งมักถูกประมาณการไว้สูงเกินจริง · ใช้รูปพหูพจน์'),
  ]},
 # ชุดที่ 12
 {'box': ['merged', 'acquired', 'took over', 'bid for',
          'walked away', 'held talks', 'called off', 'was liquidated'],
  'items': [
   ('The two regional practices ………… four years ago and now share one audit methodology.',
    'merged',
    u'รวมกิจการเข้าด้วยกัน · merge ใช้เป็นกริยาไม่ต้องมีกรรมได้'),
   ('After the pension problem came to light, the buyer ………… .',
    'walked away',
    u'ถอนตัวจากดีล · walk away เป็นสำนวนที่ใช้กับการเลิกเจรจากลางคัน'),
   ('The group ………… a smaller competitor for ninety million in cash.',
    'acquired',
    u'ซื้อกิจการมา · acquire ตามด้วยกรรมโดยตรง ไม่ต้องมีบุพบท'),
   ('The talks were ………… in December when the two sides could not agree on price.',
    'called off',
    u'ถูกยกเลิก · call off ใช้ในรูป passive ได้ตามที่เห็นในประโยคนี้'),
   ('Both boards ………… for six weeks before anything was announced.',
    'held talks',
    u'เจรจากัน · hold talks เป็นคู่คำที่ใช้กับการเจรจาระดับบริษัท'),
  ]},
 # ชุดที่ 13
 {'box': ['non-controlling interest', 'holding company', 'subsidiary', 'associate',
          'group accounts', 'consolidation', 'disposal', 'carrying amount'],
  'items': [
   ('A ………… owns the shares but carries on no trade of its own.',
    'holding company',
    u'บริษัทที่ถือหุ้นบริษัทอื่นไว้เฉย ๆ ไม่ได้ประกอบธุรกิจเอง'),
   ('Once control passed, the smaller firm became a wholly owned ………… .',
    'subsidiary',
    u'บริษัทย่อยที่ถูกถือหุ้นทั้งหมด ต้องนำมาจัดทำงบการเงินรวม'),
   ('A twenty-five percent holding with board representation is treated as an ………… .',
    'associate',
    u'บริษัทร่วม คือมีอิทธิพลอย่างมีนัยสำคัญแต่ยังไม่ถึงขั้นควบคุม'),
   ('The ………… must include every company the parent controls.',
    'group accounts',
    u'งบการเงินรวมของทั้งกลุ่ม · ใช้รูปพหูพจน์เสมอ'),
   ('The ………… of the investment was written down by twelve million.',
    'carrying amount',
    u'มูลค่าตามบัญชีที่แสดงอยู่ในงบ ณ วันนั้น'),
  ]},
 # ชุดที่ 14
 {'box': ['due diligence', 'valuation', 'goodwill', 'impairment',
          'earnings multiple', 'cash offer', 'target company', 'integration'],
  'items': [
   ('The price was arrived at by applying an ………… of nine to last year’s profit.',
    'earnings multiple',
    u'ตัวคูณกำไรที่ใช้ตีมูลค่ากิจการ เช่น เก้าเท่าของกำไร'),
   ('Shareholders were offered eight pounds a share in a straight ………… , with no shares involved.',
    'cash offer',
    u'ข้อเสนอที่จ่ายเป็นเงินสดล้วน ตรงข้ามกับ share swap'),
   ('The excess paid over the fair value of the net assets was recognised as ………… .',
    'goodwill',
    u'ค่าความนิยม คือส่วนที่จ่ายเกินมูลค่ายุติธรรมของสินทรัพย์สุทธิ'),
   ('Three years later that same balance failed the annual test and an ………… was recorded.',
    'impairment',
    u'การด้อยค่า · ค่าความนิยมไม่ตัดจำหน่าย แต่ต้องทดสอบการด้อยค่าทุกปี'),
   ('The ………… had been loss-making for two years before the approach was made.',
    'target company',
    u'กิจการเป้าหมายที่ถูกเสนอซื้อ'),
  ]},
 # ชุดที่ 15
 {'box': ['hostile takeover', 'friendly takeover', 'predator', 'defence document',
          'shareholders', 'undervalued', 'premium', 'bid'],
  'items': [
   ('The directors refused to recommend the offer, so it became a ………… .',
    'hostile takeover',
    u'การเข้าครอบงำกิจการโดยที่คณะกรรมการไม่เห็นชอบ'),
   ('The board published a ………… arguing that the offer was far too low.',
    'defence document',
    u'เอกสารที่คณะกรรมการออกมาชี้แจงเพื่อคัดค้านข้อเสนอ'),
   ('The buyer paid a ………… of thirty percent over the price before the approach.',
    'premium',
    u'ส่วนเกินที่ผู้ซื้อยอมจ่ายเหนือราคาตลาดก่อนมีข่าว'),
   ('The board said the offer left the company badly ………… .',
    'undervalued',
    u'ถูกตีมูลค่าต่ำกว่าที่ควรจะเป็น · เป็น participle ที่ทำหน้าที่เหมือน adjective'),
   ('In the end the ………… voted narrowly in favour.',
    'shareholders',
    u'ผู้ถือหุ้นเป็นผู้ลงมติชี้ขาด ไม่ใช่คณะกรรมการ'),
  ]},
]

# ── Part II · A ── ตัดสินว่าวลีนามเรียงคำถูกหรือไม่ · ชุดที่ 6 ถึง 15
# (วลี, เรียงถูกไหม, รูปที่ถูกถ้าผิด, คำอธิบาย)
# จำนวนข้อที่เรียงถูกไล่เป็น 2 4 3 1 4 2 3 1 4 2
P2A = [
 # ชุดที่ 6 · ถูก 2 ข้อ
 [('a highly experienced audit partner', True, '',
   u'highly ขยาย experienced แล้วตามด้วยนามขยาย audit จบที่ head noun partner'),
  ('a flow monthly cash statement', False, 'a monthly cash flow statement',
   u'นามขยายต้องเรียงติดกันเป็น cash flow และ adjective monthly อยู่หน้าสุด'),
  ('a completely inadequate control environment', True, '',
   u'completely ขยาย inadequate แล้วตามด้วยนามขยาย control จบที่ environment'),
  ('a risk seriously assessment flawed', False, 'a seriously flawed risk assessment',
   u'คำขยายทั้งหมดต้องอยู่หน้าคำนาม และ adverb ต้องติดหน้า adjective เสมอ'),
  ('an overdue long payment reminder', False, 'a long overdue payment reminder',
   u'long overdue เป็นคู่ที่แยกกันไม่ได้ ต้องอยู่ติดกันและเรียงตามนี้'),
 ],
 # ชุดที่ 7 · ถูก 4 ข้อ
 [('a carefully drafted engagement letter', True, '',
   u'carefully ขยาย drafted ซึ่งเป็น -ed participle แล้วตามด้วย engagement และ letter'),
  ('an unusually large year-end adjustment', True, '',
   u'unusually ขยาย large แล้วตามด้วยนามขยาย year-end จบที่ adjustment'),
  ('a five-year lease agreement', True, '',
   u'ตัวเลขกับหน่วยเวลาที่ขยายคำนาม ใช้รูปเอกพจน์และมีขีดกลาง เขียนแบบนี้ถูกแล้ว'),
  ('a party related transaction disclosure', False, 'a related party transaction disclosure',
   u'related ต้องขยาย party จึงต้องอยู่หน้า party ไม่ใช่ตามหลัง'),
  ('a fully depreciated delivery vehicle', True, '',
   u'fully ขยาย depreciated แล้วตามด้วยนามขยาย delivery จบที่ vehicle'),
 ],
 # ชุดที่ 8 · ถูก 3 ข้อ
 [('a widely used accounting package', True, '',
   u'widely ขยาย used แล้วตามด้วยนามขยาย accounting จบที่ package'),
  ('a sheet balance date event', False, 'a balance sheet date event',
   u'นามขยายสามตัวต้องเรียงเป็น balance sheet date ตามลำดับความหมาย'),
  ('an entirely automated approval process', True, '',
   u'entirely ขยาย automated แล้วตามด้วยนามขยาย approval จบที่ process'),
  ('a significantly overstated closing inventory', True, '',
   u'significantly ขยาย overstated แล้วตามด้วย closing จบที่ head noun inventory'),
  ('a control internal weakness serious', False, 'a serious internal control weakness',
   u'คำขยายทั้งหมดอยู่หน้าคำนาม และนามขยายต้องเรียงเป็น internal control'),
 ],
 # ชุดที่ 9 · ถูก 1 ข้อ
 [('a rate exchange sudden movement', False, 'a sudden exchange rate movement',
   u'adjective sudden อยู่หน้าสุด แล้วตามด้วยนามขยาย exchange rate ตามลำดับ'),
  ('a very unique selling point', False, 'a truly unique selling point',
   u'unique เป็น adjective ที่สุดทางแล้ว ใช้กับ truly หรือ absolutely ไม่ใช่ very'),
  ('an immediately payable tax liability', True, '',
   u'immediately ขยาย payable แล้วตามด้วยนามขยาย tax จบที่ liability'),
  ('a poorly report written audit', False, 'a poorly written audit report',
   u'adverb ต้องติดหน้า adjective และคำขยายทั้งหมดอยู่หน้าคำนาม'),
  ('a term short bank loan', False, 'a short term bank loan',
   u'short term เป็นคู่ที่ต้องอยู่ติดกันและเรียงตามนี้เสมอ'),
 ],
 # ชุดที่ 10 · ถูก 4 ข้อ
 [('a strictly confidential board paper', True, '',
   u'strictly ขยาย confidential แล้วตามด้วยนามขยาย board จบที่ paper'),
  ('a rapidly growing customer base', True, '',
   u'rapidly ขยาย growing ซึ่งเป็น -ing participle แล้วตามด้วย customer และ base'),
  ('a three-month payment term', True, '',
   u'three-month ใช้รูปเอกพจน์และมีขีดกลาง ถูกต้องแล้ว'),
  ('an independently verified bank balance', True, '',
   u'independently ขยาย verified แล้วตามด้วยนามขยาย bank จบที่ balance'),
  ('a flow improved forecast cash', False, 'an improved cash flow forecast',
   u'คำขยายทั้งหมดอยู่หน้าคำนาม และนามขยายต้องเรียงเป็น cash flow'),
 ],
 # ชุดที่ 11 · ถูก 2 ข้อ
 [('a value fair measurement reliable', False, 'a reliable fair value measurement',
   u'คำขยายทั้งหมดอยู่หน้าคำนาม และนามขยายต้องเรียงเป็น fair value'),
  ('a heavily indebted group company', True, '',
   u'heavily ขยาย indebted แล้วตามด้วยนามขยาย group จบที่ company'),
  ('a written recently accounting manual', False, 'a recently written accounting manual',
   u'adverb ต้องอยู่หน้า participle ไม่ใช่ตามหลัง · recently ต้องมาก่อน written'),
  ('a management very useful letter', False, 'a very useful management letter',
   u'adverb ต้องติดหน้า adjective · very ต้องมาก่อน useful ไม่ใช่ไปคั่นหลัง management'),
  ('a clearly stated accounting policy', True, '',
   u'clearly ขยาย stated แล้วตามด้วยนามขยาย accounting จบที่ policy'),
 ],
 # ชุดที่ 12 · ถูก 3 ข้อ
 [('a legally binding purchase agreement', True, '',
   u'legally ขยาย binding แล้วตามด้วยนามขยาย purchase จบที่ agreement'),
  ('an unexpectedly high effective tax rate', True, '',
   u'unexpectedly ขยาย high แล้วตามด้วย effective และนามขยาย tax จบที่ rate'),
  ('a sample size statistically valid', False, 'a statistically valid sample size',
   u'คำขยายทั้งหมดต้องอยู่หน้าคำนาม ภาษาอังกฤษไม่วางไว้ข้างหลังแบบภาษาไทย'),
  ('a fully funded pension scheme', True, '',
   u'fully ขยาย funded แล้วตามด้วยนามขยาย pension จบที่ scheme'),
  ('an error posting simple journal', False, 'a simple journal posting error',
   u'นามขยายเรียงเป็น journal posting แล้ว adjective simple อยู่หน้าสุด'),
 ],
 # ชุดที่ 13 · ถูก 1 ข้อ
 [('a going seriously concern doubt', False, 'a serious going concern doubt',
   u'going concern เป็นคู่ที่แยกไม่ได้ และตรงนี้ต้องใช้ adjective serious ขยาย doubt'),
  ('an audit two-days programme', False, 'a two-day audit programme',
   u'ตัวเลขกับหน่วยเวลาที่ขยายคำนามใช้รูปเอกพจน์เสมอ · two-day ไม่ใช่ two-days'),
  ('a correctly classified finance lease', True, '',
   u'correctly ขยาย classified แล้วตามด้วยนามขยาย finance จบที่ lease'),
  ('a flow statement cash consolidated', False, 'a consolidated cash flow statement',
   u'คำขยายทั้งหมดอยู่หน้าคำนาม และนามขยายต้องเรียงเป็น cash flow'),
  ('a very complete set of records', False, 'an absolutely complete set of records',
   u'complete เป็น adjective ที่สุดทางแล้ว ใช้กับ absolutely ไม่ใช่ very'),
 ],
 # ชุดที่ 14 · ถูก 4 ข้อ
 [('a newly issued accounting standard', True, '',
   u'newly ขยาย issued แล้วตามด้วยนามขยาย accounting จบที่ standard'),
  ('a tightly controlled petty cash float', True, '',
   u'tightly ขยาย controlled แล้วตามด้วยนามขยาย petty cash จบที่ float'),
  ('a receivables ageing detailed report', False, 'a detailed receivables ageing report',
   u'adjective detailed ต้องอยู่หน้านามขยายทั้งหมด ไม่ใช่ไปแทรกกลาง'),
  ('a widely respected finance director', True, '',
   u'widely ขยาย respected แล้วตามด้วยนามขยาย finance จบที่ director'),
  ('a thirty-day credit period', True, '',
   u'thirty-day ใช้รูปเอกพจน์และมีขีดกลาง ถูกต้องแล้ว'),
 ],
 # ชุดที่ 15 · ถูก 2 ข้อ
 [('an internal well designed check', False, 'a well designed internal check',
   u'well ต้องติดหน้า designed และคู่นี้ต้องอยู่หน้า adjective internal'),
  ('a materially misstated revenue figure', True, '',
   u'materially ขยาย misstated แล้วตามด้วยนามขยาย revenue จบที่ figure'),
  ('a sheet off balance arrangement', False, 'an off balance sheet arrangement',
   u'off balance sheet เป็นชุดคำที่ต้องเรียงตามนี้เสมอ และต้องใช้ an เพราะขึ้นต้นด้วยสระ'),
  ('a payable accounts ledger reconciled', False, 'a reconciled accounts payable ledger',
   u'คำขยายทั้งหมดอยู่หน้าคำนาม และนามขยายต้องเรียงเป็น accounts payable'),
  ('a highly automated payroll system', True, '',
   u'highly ขยาย automated แล้วตามด้วยนามขยาย payroll จบที่ system'),
 ],
]

# ── Part II · B ── เลือกรูปกริยาที่ถูกต้อง เรื่องการคาดการณ์และความน่าจะเป็น
# (ประโยค, ตัวเลือกทั้งหมดโดยตัวแรกคือคำตอบ, เหตุผล) · ชุดที่ 6 ถึง 15
P2B = [
 # ชุดที่ 6
 [('By Friday the team ………… all the bank confirmations.',
   ['will have sent', 'will be sending', 'sends', 'is sending'],
   u'เจอ by + เวลา ให้ใช้ future perfect เสมอ เพราะ by แปลว่าภายในก่อนถึง ซึ่งบอกว่าเสร็จแล้ว'),
  ('At three o’clock tomorrow I ………… the inventory count at the warehouse.',
   ['will be observing', 'will have observed', 'observe', 'have observed'],
   u'at + เวลา ชี้จุดเวลาแล้วถามว่าตอนนั้นกำลังทำอะไรอยู่ จึงใช้ future continuous'),
  ('The safe was locked all night, so the cash ………… been taken after closing.',
   ['can’t have', 'must have', 'might have', 'should have'],
   u'มีหลักฐานค้านชัดเจน จึงมั่นใจว่าเป็นไปไม่ได้ ใช้ can’t have'),
  ('If the client ………… the deadline, we will have to extend the fieldwork.',
   ['misses', 'will miss', 'missed', 'would miss'],
   u'first conditional คือ If + V1 แล้ว will + V1 · ห้ามใส่ will ในประโยค if เด็ดขาด'),
  ('There is ………… doubt that the provision will have to be increased.',
   ['little', 'few', 'a little', 'less'],
   u'doubt เป็นนามนับไม่ได้จึงใช้ little · little เฉย ๆ แปลว่าแทบไม่มี ส่วน a little แปลว่าพอมีอยู่บ้าง'),
 ],
 # ชุดที่ 7
 [('By this time next year, the group ………… to the new reporting system.',
   ['will have moved', 'will be moving', 'moves', 'is moving'],
   u'by this time + เวลา บอกว่าเสร็จก่อนถึงจุดนั้น จึงใช้ future perfect'),
  ('We ………… the draft report while you are travelling, so expect comments on Monday.',
   ['will be preparing', 'will have prepared', 'prepare', 'prepared'],
   u'while + ประโยค บอกช่วงที่กำลังทำอยู่ จึงใช้ future continuous'),
  ('His coat is on and the car is outside. He is ………… leave.',
   ['about to', 'bound to', 'due to', 'likely to'],
   u'about to แปลว่ากำลังจะเกิดในอีกไม่กี่วินาที ซึ่งตรงกับสัญญาณที่เห็นตรงหน้า'),
  ('It is ………… that the tax rate will change before the year end.',
   ['unlikely', 'unlike', 'dislike', 'unlikely to'],
   u'It is unlikely that + ประโยคเต็ม · ถ้าจะใช้ unlikely to ต้องมีประธานนำหน้า เช่น The rate is unlikely to change'),
  ('The invoice is dated last March, so it ………… have been paid by now.',
   ['should', 'can’t', 'might not', 'needn’t'],
   u'should have ใช้กับสิ่งที่คาดว่าน่าจะเกิดขึ้นแล้วตามกำหนด แต่ยังไม่ได้ยืนยัน'),
 ],
 # ชุดที่ 8
 [('Look at these figures. The company ………… meet its loan covenant.',
   ['isn’t going to', 'won’t have', 'wasn’t going to', 'doesn’t go to'],
   u'มีหลักฐานตรงหน้าคือตัวเลขในมือ จึงใช้ going to · will ใช้เมื่อเป็นความเห็นหรือตัดสินใจเดี๋ยวนั้น'),
  ('By the end of the audit, we ………… more than four hundred hours on this client.',
   ['will have spent', 'will be spending', 'spend', 'are spending'],
   u'by the end of + เวลา ใช้ future perfect เพราะนับรวมทั้งหมดถึงจุดนั้น'),
  ('The partner ………… sign the report until the going concern note is agreed.',
   ['won’t', 'will', 'isn’t', 'doesn’t'],
   u'won’t + V1 ใช้กับการปฏิเสธที่จะทำสิ่งใดสิ่งหนึ่งจนกว่าเงื่อนไขจะครบ'),
  ('If we ………… found the error sooner, we would not have reprinted the accounts.',
   ['had', 'have', 'would have', 'did'],
   u'third conditional คือ If + had + V3 แล้ว would have + V3 · ใช้กับเรื่องที่ไม่ได้เกิดขึ้นในอดีต'),
  ('Interest rates are ………… to fall slightly during the second half of the year.',
   ['expected', 'expecting', 'expectation', 'expect'],
   u'be expected to + V1 เป็นรูป passive ที่ใช้พยากรณ์ · expecting แปลว่าตัวประธานเป็นคนคาด ผิดความหมาย'),
 ],
 # ชุดที่ 9
 [('This time on Thursday, the committee ………… our findings.',
   ['will be reading', 'will have read', 'reads', 'has read'],
   u'this time + เวลา ชี้จุดเวลาในอนาคตแล้วถามว่าตอนนั้นกำลังทำอะไรอยู่'),
  ('The file was signed off yesterday, so the review points ………… been cleared.',
   ['must have', 'can’t have', 'needn’t have', 'shouldn’t have'],
   u'มีหลักฐานว่าปิดงานแล้ว จึงมั่นใจสูงราว 80 เปอร์เซ็นต์ ใช้ must have'),
  ('There is ………… to be a shortage of qualified staff next year.',
   ['sure', 'surely', 'sureness', 'surely going'],
   u'รูปที่ถูกคือ There is sure to be + คำนาม · ขาด to be ไม่ได้ และ surely เป็น adverb วางตรงนี้ไม่ได้'),
  ('Unless the supplier ………… the goods this week, we will miss the cut-off.',
   ['delivers', 'will deliver', 'delivered', 'would deliver'],
   u'unless ใช้แทน if not และตามด้วย V1 · ห้ามใส่ will เหมือนประโยค if ทั่วไป'),
  ('By two thousand and forty, paper invoices ………… almost entirely.',
   ['will have disappeared', 'will be disappearing', 'disappear', 'are disappearing'],
   u'by + ปี บอกว่าเสร็จสิ้นก่อนถึงปีนั้น จึงใช้ future perfect'),
 ],
 # ชุดที่ 10
 [('From Monday, we ………… the new approval limits at every branch.',
   ['will be applying', 'will have applied', 'have applied', 'applied'],
   u'from + วัน แปลว่าเริ่มตั้งแต่วันนั้นแล้วทำต่อเนื่อง จึงใช้ future continuous'),
  ('The deadline is tomorrow and he has not started. He is ………… be late.',
   ['bound to', 'about to', 'unlikely to', 'due to'],
   u'bound to แปลว่าแน่นอนว่าจะ ใช้กับผลที่เลี่ยงไม่ได้จากสถานการณ์ที่เห็นอยู่'),
  ('The train ………… arrive at nine, according to the timetable.',
   ['is due to', 'is about to', 'is bound to', 'is likely to'],
   u'be due to ใช้กับสิ่งที่มีกำหนดเวลาไว้แน่นอนอยู่แล้ว เช่น ตารางเวลา'),
  ('The results ………… be announced on the fourteenth of next month.',
   ['are to', 'are about to', 'are going', 'will to'],
   u'be to + V1 ใช้กับกำหนดการที่เป็นทางการ พบบ่อยในข่าวและประกาศของบริษัท'),
  ('It is ………… unlikely that the merger will be approved this year.',
   ['highly', 'high', 'height', 'highness'],
   u'highly unlikely เป็นคู่ที่ใช้ด้วยกันเสมอ · ช่องนี้ต้องเป็น adverb จึงใช้ high ไม่ได้'),
 ],
 # ชุดที่ 11
 [('By the time you read this, the payment ………… already been made.',
   ['will have', 'will be', 'has', 'is having'],
   u'by the time + ประโยค ใช้ future perfect · ประโยคพูดถึงอนาคต จึงใช้ has ไม่ได้'),
  ('Next Tuesday afternoon, the team ………… the year-end files to the archive.',
   ['will be moving', 'will have moved', 'moves', 'moved'],
   u'ระบุช่วงเวลาในอนาคตแล้วถามว่าตอนนั้นกำลังทำอะไรอยู่ จึงใช้ future continuous'),
  ('She has missed every deadline this year, so she is ………… miss this one.',
   ['bound to', 'unlikely to', 'about to', 'due to'],
   u'bound to ใช้กับสิ่งที่เกิดซ้ำจนคาดเดาได้ · unlikely to แปลกลับด้าน ผิดความหมาย'),
  ('The system shows the file as opened, so someone ………… have read it.',
   ['must', 'can’t', 'needn’t', 'shouldn’t'],
   u'มีหลักฐานจากระบบ จึงมั่นใจสูง ใช้ must have · can’t have ใช้เมื่อหลักฐานค้าน'),
  ('If the board ………… the budget tonight, we can start work tomorrow.',
   ['approves', 'will approve', 'approved', 'would approve'],
   u'first conditional · ห้ามใส่ will ในประโยค if แม้ประโยคหลักจะใช้ can ก็ตาม'),
 ],
 # ชุดที่ 12
 [('It is ………… possible that the group will need a new bank facility.',
   ['perfectly', 'perfect', 'perfection', 'perfectly going'],
   u'perfectly possible เป็นคู่ที่ใช้ด้วยกันเสมอ · ช่องนี้ต้องเป็น adverb ขยาย adjective'),
  ('By the end of the week, the partner ………… the file twice.',
   ['will have reviewed', 'will be reviewing', 'reviews', 'is reviewing'],
   u'by the end of + เวลา ใช้ future perfect เพราะนับจำนวนครั้งรวมถึงจุดนั้น'),
  ('Don’t ring me on Thursday morning because I ………… at the client’s warehouse.',
   ['will be', 'will have been', 'am', 'was'],
   u'ช่วงเวลาในอนาคตที่กำลังอยู่ที่ใดที่หนึ่ง ใช้ future continuous หรือ will be + สถานที่'),
  ('The letter was posted three weeks ago, so it ………… still be in the post.',
   ['can’t', 'must', 'should', 'will'],
   u'สามสัปดาห์นานเกินไป จึงมั่นใจว่าเป็นไปไม่ได้ ใช้ can’t'),
  ('The company ………… report a profit this year unless sales recover quickly.',
   ['won’t', 'doesn’t', 'isn’t', 'hasn’t'],
   u'พยากรณ์อนาคตในรูปปฏิเสธ ใช้ won’t + V1'),
 ],
 # ชุดที่ 13
 [('At this time tomorrow, the shareholders ………… on the resolution.',
   ['will be voting', 'will have voted', 'vote', 'voted'],
   u'at this time + เวลา ชี้จุดเวลา จึงใช้ future continuous'),
  ('By December the new auditors ………… their first full year on the group.',
   ['will have completed', 'will be completing', 'complete', 'are completing'],
   u'by + เดือน บอกว่าเสร็จก่อนถึงจุดนั้น จึงใช้ future perfect'),
  ('There is every ………… that the contract will be renewed.',
   ['likelihood', 'likely', 'like', 'liking'],
   u'There is every likelihood that + ประโยค · หลัง every ต้องเป็นคำนาม จึงใช้ likely ไม่ได้'),
  ('If the rate ………… by one percent, our interest cost would rise by two million.',
   ['rose', 'rises', 'will rise', 'has risen'],
   u'second conditional คือ If + V2 แล้ว would + V1 · ใช้กับเรื่องสมมติที่ยังไม่เกิด'),
  ('The office is dark and the door is locked, so they ………… have gone home.',
   ['must', 'can’t', 'might not', 'needn’t'],
   u'มีหลักฐานสองอย่างตรงกัน จึงมั่นใจสูง ใช้ must have'),
 ],
 # ชุดที่ 14
 [('The auditors ………… on site from the fifth to the nineteenth of next month.',
   ['will be', 'will have been', 'are being', 'have been'],
   u'ช่วงเวลาต่อเนื่องในอนาคต ใช้ will be + สถานที่ ไม่ใช่ future perfect'),
  ('By the time the accounts are filed, three months ………… since the year end.',
   ['will have passed', 'will be passing', 'pass', 'are passing'],
   u'by the time + ประโยค ใช้ future perfect เพราะนับเวลาที่ผ่านไปรวมถึงจุดนั้น'),
  ('He never checks his email, so he is ………… to have seen the request.',
   ['unlikely', 'unlike', 'not likely to', 'dislikely'],
   u'be unlikely to + V1 · ช่องนี้มี to อยู่แล้ว จึงใส่ not likely to ซ้ำไม่ได้'),
  ('The invoice ………… have been approved, because the system will not release payment otherwise.',
   ['must', 'can’t', 'needn’t', 'shouldn’t'],
   u'เหตุผลเชิงตรรกะบังคับว่าต้องเกิดขึ้นแล้ว จึงใช้ must have'),
  ('Unless the provision ………… , the auditors will qualify their opinion.',
   ['is increased', 'will be increased', 'increases to', 'had increased'],
   u'unless ตามด้วยปัจจุบันกาล ห้ามใส่ will · และตรงนี้ต้องเป็น passive เพราะประมาณการถูกปรับ'),
 ],
 # ชุดที่ 15
 [('This time next week, we ………… the closing meeting with the audit committee.',
   ['will be holding', 'will have held', 'hold', 'held'],
   u'this time next week ชี้จุดเวลาในอนาคต จึงใช้ future continuous'),
  ('By the year end, the loan ………… in full.',
   ['will have been repaid', 'will be repaying', 'repays', 'is repaying'],
   u'by + เวลา ใช้ future perfect และต้องเป็น passive เพราะเงินกู้เป็นสิ่งที่ถูกชำระ'),
  ('The forecast shows a deficit, so the directors are ………… to seek new funding.',
   ['certain', 'certainly', 'certainty', 'certainty of'],
   u'be certain to + V1 · certainly เป็น adverb และ certainty เป็นคำนาม วางตรงนี้ไม่ได้'),
  ('If the client ………… us last week, we could have finished on time.',
   ['had told', 'told', 'has told', 'would tell'],
   u'third conditional คือ If + had + V3 แล้ว could have + V3 · เป็นเรื่องที่ไม่ได้เกิดขึ้นจริง'),
  ('There ………… be further consolidation in this industry, in my view.',
   ['is likely to', 'is likely', 'likely to', 'is like to'],
   u'There is likely to be + คำนาม · ขาด to be ไม่ได้ และ like ไม่ใช่ likely'),
 ],
]
