# -*- coding: utf-8 -*-
u"""คลังคำศัพท์ของวิชาภาษาอังกฤษ · ส่วนที่ 2 คือ Unit 12 Mergers and Acquisitions

รูปแบบเดียวกับ tools/vocab-1.py
"""

GROUPS = [

{'code': 'core6', 'name': u'หกคำหลัก', 'unit': 'Unit 12', 'items': [
 ('joint venture', u'กิจการร่วมค้า',
  u'สองบริษัทขึ้นไปลงเงินตั้งกิจการใหม่ร่วมกัน โดยไม่มีใครซื้อใคร · คำใบ้อยู่ที่คำว่า joint '
  u'และเพราะไม่มีฝ่ายไหนควบคุม จึงไม่ต้องนำมาจัดทำงบการเงินรวม ใช้วิธีส่วนได้เสียแทน',
  'Neither partner wanted full control, so they set up a fifty-fifty joint venture.',
  u'ไม่มีหุ้นส่วนฝ่ายใดอยากควบคุมเต็มที่ จึงตั้งกิจการร่วมค้าถือคนละครึ่ง'),
 ('MBO · management buyout', u'ผู้บริหารซื้อกิจการที่ตัวเองทำงานอยู่',
  u'ผู้บริหารกู้เงินมาซื้อกิจการที่ตนบริหาร · ความเสี่ยงที่เพิ่มขึ้นมาจากโครงสร้างเงินกู้ ไม่ใช่จากตัวธุรกิจ',
  'Four senior managers borrowed against the company assets in a management buyout.',
  u'ผู้บริหารอาวุโสสี่คนกู้เงินโดยใช้สินทรัพย์ของบริษัทค้ำ ในการซื้อกิจการโดยผู้บริหาร'),
 ('merger', u'การควบรวม',
  u'รวมกันเป็นบริษัทใหญ่ขึ้น มักเกิดชื่อใหม่ และทั้งสองฝ่ายมักมีขนาดใกล้เคียงกัน',
  'Both companies were a similar size, so the deal was presented as a merger of equals.',
  u'ทั้งสองบริษัทมีขนาดใกล้เคียงกัน ดีลนี้จึงถูกนำเสนอว่าเป็นการควบรวมของผู้เท่าเทียม'),
 ('takeover · acquisition', u'การเข้าซื้อกิจการ',
  u'ซื้อหุ้นจนได้อำนาจควบคุม มักเกิน 50% · ต่างจาก merger ตรงที่มีผู้ซื้อกับผู้ถูกซื้อชัดเจน',
  'The acquisition was completed in September and consolidated from that date.',
  u'การซื้อกิจการเสร็จสมบูรณ์ในเดือนกันยายนและนำมารวมงบตั้งแต่วันนั้น'),
 ('bid', u'การเสนอราคาซื้อหุ้น',
  u'แค่ยื่นข้อเสนอ ยังไม่ได้ซื้อ · อาจถูกปฏิเสธ ถูกเพิ่มราคา หรือถอนได้',
  'The takeover bid lapsed because fewer than half the shareholders accepted it.',
  u'ข้อเสนอซื้อกิจการตกไปเพราะผู้ถือหุ้นตอบรับไม่ถึงครึ่ง'),
 ('stake', u'สัดส่วนการถือหุ้น · เงินที่ลงทุนไว้',
  u'สิ่งที่ถืออยู่แล้วจริง ต่างจาก bid ซึ่งยังเป็นแค่ข้อเสนอ · ใช้กับ take hold build up sell',
  'The fund increased its stake from twelve percent to twenty-nine percent in two months.',
  u'กองทุนเพิ่มสัดส่วนการถือหุ้นจากสิบสองเปอร์เซ็นต์เป็นยี่สิบเก้าภายในสองเดือน'),
]},

{'code': 'verbs', 'name': u'กริยาที่ใช้คู่กัน', 'unit': 'Unit 12', 'items': [
 ('take a stake in', u'เข้าถือหุ้นใน',
  u'เริ่มถือหุ้นบางส่วน ยังไม่ถึงขั้นควบคุม · ตามด้วย in เสมอ',
  'The investor took a stake in the start-up without seeking board seats.',
  u'นักลงทุนเข้าถือหุ้นในสตาร์ตอัปโดยไม่ได้ขอที่นั่งในคณะกรรมการ'),
 ('hold a stake', u'ถือหุ้นอยู่',
  u'บอกสถานะปัจจุบัน ไม่ใช่การกระทำ · จึงไม่ต้องมี in ตามหลังเสมอไป',
  'The founding family still holds a twelve percent stake.',
  u'ครอบครัวผู้ก่อตั้งยังถือหุ้นอยู่สิบสองเปอร์เซ็นต์'),
 ('build up a stake', u'ทยอยสะสมหุ้น',
  u'ค่อย ๆ ซื้อทีละน้อยเพื่อไม่ให้ราคาขยับหรือไม่ให้ต้องเปิดเผย',
  'The bidder quietly built up a stake just under the disclosure threshold.',
  u'ผู้เสนอซื้อค่อย ๆ สะสมหุ้นเงียบ ๆ ให้ต่ำกว่าเกณฑ์ที่ต้องเปิดเผยนิดเดียว'),
 ('sell a stake', u'ขายหุ้นที่ถืออยู่',
  u'ขายออกทั้งหมดหรือบางส่วนก็ได้ · คู่ตรงข้ามของ take a stake',
  'They sold their stake over four months at a small profit.',
  u'พวกเขาทยอยขายหุ้นที่ถืออยู่ภายในสี่เดือนโดยได้กำไรเล็กน้อย'),
 ('make a bid for', u'ยื่นข้อเสนอซื้อ',
  u'ตามด้วย for เสมอ · ใช้ make ไม่ใช่ do',
  'In March a European group made a bid for our client worth four hundred million euros.',
  u'ในเดือนมีนาคม กลุ่มทุนยุโรปยื่นข้อเสนอซื้อลูกค้าของเรามูลค่าสี่ร้อยล้านยูโร'),
 ('launch a bid', u'เปิดฉากเสนอซื้อ',
  u'เน้นการเริ่มต้นอย่างเป็นทางการและเปิดเผย · มักใช้กับ hostile bid',
  'They launched a hostile bid after the board refused twice.',
  u'พวกเขาเปิดฉากเสนอซื้อแบบไม่เป็นมิตรหลังคณะกรรมการปฏิเสธสองครั้ง'),
 ('accept a bid', u'ตอบรับข้อเสนอ',
  u'ผู้ที่ตอบรับคือผู้ถือหุ้น ไม่ใช่คณะกรรมการ · คณะกรรมการทำได้แค่แนะนำ',
  'Shareholders voted to accept the bid at the meeting in November.',
  u'ผู้ถือหุ้นลงมติตอบรับข้อเสนอในการประชุมเดือนพฤศจิกายน'),
 ('reject a bid', u'ปฏิเสธข้อเสนอ',
  u'เหตุผลที่ใช้บ่อยที่สุดคือราคาต่ำกว่ามูลค่าที่แท้จริง',
  'The board rejected the bid within nine days, saying it undervalued the assets.',
  u'คณะกรรมการปฏิเสธข้อเสนอภายในเก้าวัน โดยบอกว่าตีมูลค่าสินทรัพย์ต่ำเกินไป'),
 ('raise a bid', u'เพิ่มราคาที่เสนอ',
  u'มักเกิดหลังถูกปฏิเสธ หรือเมื่อมีผู้เสนอซื้อรายอื่นเข้ามา',
  'The bidder raised the offer twice before the shareholders agreed.',
  u'ผู้เสนอซื้อเพิ่มราคาสองครั้งก่อนที่ผู้ถือหุ้นจะตกลง'),
 ('withdraw a bid', u'ถอนข้อเสนอ',
  u'ถอนได้ถ้าเงื่อนไขไม่ครบ เช่น ผู้ถือหุ้นตอบรับไม่ถึงเกณฑ์ที่ตั้งไว้',
  'The bidder withdrew the bid when the acceptance condition could not be met.',
  u'ผู้เสนอซื้อถอนข้อเสนอเมื่อเงื่อนไขการตอบรับทำไม่ได้ตามที่กำหนด'),
 ('target a company', u'เล็งบริษัทเป็นเป้า',
  u'target ต้องตามด้วยสิ่งที่เป็นเป้าหมาย ซึ่งคือบริษัท ไม่ใช่การกระทำอย่าง takeover',
  'The fund targeted three companies in the same market sector.',
  u'กองทุนเล็งบริษัทสามแห่งในภาคส่วนตลาดเดียวกันไว้เป็นเป้า'),
 ('acquire a company', u'ซื้อกิจการ',
  u'เป็นทางการกว่า buy · คำนามคือ acquisition',
  'The group acquired a regional logistics firm for three hundred and ten million.',
  u'กลุ่มบริษัทซื้อกิจการขนส่งภูมิภาคด้วยราคาสามร้อยสิบล้าน'),
 ('take over a company', u'เข้าครอบครองกิจการ',
  u'เขียนแยกสองคำเมื่อเป็นกริยา · เขียนติดกันเป็น takeover เมื่อเป็นคำนาม กับดักนี้ออกสอบบ่อย',
  'A listed group took over the family firm in the summer.',
  u'กลุ่มบริษัทจดทะเบียนเข้าครอบครองกิจการของครอบครัวในช่วงฤดูร้อน'),
 ('merge with', u'ควบรวมกับ',
  u'ตามด้วย with เสมอ · ใช้เมื่อสองฝ่ายรวมกัน ไม่ใช่ฝ่ายหนึ่งซื้ออีกฝ่าย',
  'The two audit practices merged last year and now operate under a single name.',
  u'สำนักงานสอบบัญชีสองแห่งควบรวมกันเมื่อปีที่แล้วและใช้ชื่อเดียวกันแล้ว'),
 ('set up a joint venture', u'ตั้งกิจการร่วมค้า',
  u'set up ใช้กับสิ่งที่ก่อตั้งขึ้นใหม่ · จะใช้กับหุ้นหรือข้อเสนอซื้อไม่ได้',
  'The two firms set up a joint venture to build the battery plant.',
  u'สองบริษัทตั้งกิจการร่วมค้าเพื่อสร้างโรงงานแบตเตอรี่'),
 ('make an acquisition', u'เข้าซื้อกิจการ',
  u'ใช้ make กับคำนาม acquisition · ถ้าใช้กริยาให้พูดว่า acquire ตรง ๆ',
  'We plan to make two acquisitions before the end of the financial year.',
  u'เราวางแผนจะเข้าซื้อกิจการสองแห่งก่อนสิ้นปีบัญชี'),
]},

{'code': 'maextra', 'name': u'ศัพท์ M and A เพิ่มเติม', 'unit': 'Unit 12', 'items': [
 ('shareholder', u'ผู้ถือหุ้น',
  u'อเมริกันใช้ stockholder · เป็นผู้ตัดสินใจรับหรือไม่รับข้อเสนอซื้อ ไม่ใช่คณะกรรมการ',
  'The shareholders approved the deal at a meeting held in November.',
  u'ผู้ถือหุ้นอนุมัติดีลในการประชุมเดือนพฤศจิกายน'),
 ('share price', u'ราคาหุ้น',
  u'ใช้เป็นฐานคำนวณส่วนเพิ่มที่ผู้ซื้อยอมจ่าย · ขยับทันทีเมื่อข่าวดีลออก',
  'The share price rose eight percent on the news.',
  u'ราคาหุ้นขึ้นแปดเปอร์เซ็นต์เมื่อข่าวออก'),
 ('subsidiary', u'บริษัทย่อย',
  u'บริษัทที่ถูกอีกบริษัทควบคุม · ต้องนำมาจัดทำงบการเงินรวม ต่างจากกิจการร่วมค้า',
  'Once the deal closed, the smaller firm became a wholly owned subsidiary.',
  u'เมื่อดีลปิด บริษัทที่เล็กกว่ากลายเป็นบริษัทย่อยที่ถือหุ้นทั้งหมด'),
 ('parent company', u'บริษัทแม่',
  u'คู่กับ subsidiary · เป็นผู้จัดทำงบการเงินรวม',
  'The parent company decided to divest the printing business.',
  u'บริษัทแม่ตัดสินใจขายธุรกิจโรงพิมพ์ออกไป'),
 ('bidder', u'ผู้เสนอซื้อ',
  u'ฝ่ายที่ยื่นข้อเสนอ · ถ้าท่าทีก้าวร้าวมักถูกเรียกว่า predator',
  'The bidder set an acceptance condition of seventy-five percent of shares.',
  u'ผู้เสนอซื้อตั้งเงื่อนไขการตอบรับไว้ที่เจ็ดสิบห้าเปอร์เซ็นต์ของหุ้น'),
 ('target', u'บริษัทเป้าหมาย',
  u'ฝ่ายที่ถูกเสนอซื้อ · ใช้เป็น target company ก็ได้',
  'The target rejected the first offer but agreed to open its books.',
  u'บริษัทเป้าหมายปฏิเสธข้อเสนอแรกแต่ยอมเปิดบัญชีให้ตรวจ'),
 ('due diligence', u'การตรวจสอบสถานะกิจการ',
  u'ตรวจก่อนซื้อว่ามีปัญหาซ่อนอยู่ไหม เช่น หนี้สินที่ไม่ได้บันทึกหรือคดีความ · '
  u'เป็นงานที่ผู้สอบบัญชีเข้าไปทำจริง และเวลาที่น้อยเกินไปคือความเสี่ยงคลาสสิกของดีล',
  'During due diligence the buyer accountants found warranty liabilities that had never been recorded.',
  u'ระหว่างการตรวจสอบสถานะกิจการ นักบัญชีของผู้ซื้อพบหนี้สินจากการรับประกันที่ไม่เคยถูกบันทึก'),
 ('synergy', u'การผนึกกำลัง',
  u'ผลรวมที่มากกว่าผลบวก เป็นเหตุผลยอดนิยมเวลาควบรวม · '
  u'ที่มาจากการตัดงานซ้ำซ้อนมักเกิดจริง ส่วนที่ต้องพึ่งพฤติกรรมลูกค้ามักไม่เกิด',
  'The promised synergies never appeared, and the combined cost base actually rose.',
  u'การผนึกกำลังที่สัญญาไว้ไม่เคยเกิดขึ้น และฐานต้นทุนรวมกลับสูงขึ้นด้วยซ้ำ'),
 ('economies of scale', u'การประหยัดต่อขนาด',
  u'ยิ่งผลิตมาก ต้นทุนต่อหน่วยยิ่งต่ำ · เป็นคำนามพหูพจน์เสมอ ไม่มี economy of scale',
  'Ordering in larger quantities gives economies of scale on both price and freight.',
  u'การสั่งครั้งละมากทำให้เกิดการประหยัดต่อขนาดทั้งด้านราคาและค่าขนส่ง'),
 ('premium', u'ส่วนเพิ่มเหนือราคาตลาด',
  u'ส่วนที่ผู้ซื้อยอมจ่ายเกินราคาหุ้นก่อนมีข่าว · คนละความหมายกับ premium product',
  'They paid a twenty-five percent premium over the share price before the stake was announced.',
  u'พวกเขาจ่ายส่วนเพิ่มยี่สิบห้าเปอร์เซ็นต์เหนือราคาหุ้นก่อนมีการประกาศถือหุ้น'),
 ('friendly takeover', u'การเข้าซื้อแบบเป็นมิตร',
  u'คณะกรรมการของบริษัทเป้าหมายเห็นชอบและแนะนำให้ผู้ถือหุ้นรับ',
  'Both boards recommended the deal, so this was a friendly takeover.',
  u'คณะกรรมการทั้งสองฝ่ายแนะนำให้รับดีล นี่จึงเป็นการเข้าซื้อแบบเป็นมิตร'),
 ('hostile takeover', u'การเข้าซื้อแบบไม่เป็นมิตร',
  u'กรรมการคัดค้าน ผู้ซื้อจึงข้ามไปเสนอกับผู้ถือหุ้นโดยตรง · hostile แปลว่าเป็นปฏิปักษ์',
  'Because the directors refused to recommend it, the approach became a hostile takeover.',
  u'เพราะกรรมการไม่ยอมแนะนำ การเข้าหาจึงกลายเป็นการเข้าซื้อแบบไม่เป็นมิตร'),
 ('white knight', u'อัศวินขี่ม้าขาว',
  u'ผู้ซื้อที่เป็นมิตรซึ่งถูกเชิญมาช่วยให้พ้นจากข้อเสนอที่ไม่ต้องการ',
  'A second buyer appeared on better terms, and the directors treated it as a white knight.',
  u'ผู้ซื้อรายที่สองปรากฏขึ้นพร้อมเงื่อนไขที่ดีกว่า กรรมการจึงถือว่าเป็นอัศวินขี่ม้าขาว'),
 ('poison pill', u'ยาพิษ',
  u'มาตรการที่ทำให้ตัวเองถูกซื้อยากขึ้น เช่น ให้สิทธิผู้ถือหุ้นเดิมซื้อหุ้นเพิ่มในราคาถูก',
  'The board adopted a poison pill to make a hostile bid more expensive.',
  u'คณะกรรมการใช้มาตรการยาพิษเพื่อทำให้การเสนอซื้อแบบไม่เป็นมิตรแพงขึ้น'),
 ('divest', u'ขายกิจการทิ้ง',
  u'ตรงข้ามกับ acquire · มักทำเพื่อหาเงินมาซื้อกิจการอื่นหรือตัดส่วนที่ไม่ใช่ธุรกิจหลัก',
  'The group divested its loss-making logistics arm in order to fund the purchase.',
  u'กลุ่มบริษัทขายหน่วยขนส่งที่ขาดทุนทิ้งเพื่อหาเงินมาซื้อกิจการ'),
 ('spin-off', u'การแยกกิจการออกมาตั้งใหม่',
  u'แยกหน่วยธุรกิจออกเป็นบริษัทอิสระ โดยผู้ถือหุ้นเดิมมักได้หุ้นของบริษัทใหม่ · ต่างจาก divest ที่ขายให้คนอื่น',
  'The software unit was separated in a spin-off and listed on its own.',
  u'หน่วยซอฟต์แวร์ถูกแยกออกมาตั้งใหม่และเข้าจดทะเบียนด้วยตัวเอง'),
 ('asset stripping', u'การซื้อมาเพื่อแยกขายทรัพย์สิน',
  u'ซื้อกิจการแล้วขายสินทรัพย์เป็นชิ้น ๆ เอากำไร ไม่ได้ตั้งใจดำเนินกิจการต่อ · เป็นคำเชิงลบ',
  'The buyer sold the warehouses within a year, which the press called asset stripping.',
  u'ผู้ซื้อขายคลังสินค้าออกภายในหนึ่งปี ซึ่งสื่อเรียกว่าการซื้อมาเพื่อแยกขายทรัพย์สิน'),
 ('antitrust · competition authority', u'หน่วยงานกำกับการแข่งขัน',
  u'อาจสั่งห้ามดีลที่ทำให้เกิดการผูกขาด หรือสั่งให้ขายบางส่วนออกก่อนจึงอนุญาต',
  'The competition authority cleared the deal only after the group agreed to sell two plants.',
  u'หน่วยงานกำกับการแข่งขันอนุมัติดีลก็ต่อเมื่อกลุ่มบริษัทยอมขายโรงงานสองแห่งออกไป'),
]},

]
