# -*- coding: utf-8 -*-
u"""คลังคำศัพท์ของวิชาภาษาอังกฤษ · ส่วนที่ 1 คือ Unit 2 International Marketing

ทุกคำมีครบห้าช่อง
  (คำศัพท์, คำแปลไทย, คำอธิบายภาษาไทย, ตัวอย่างประโยคภาษาอังกฤษ, คำแปลของตัวอย่าง)

คำอธิบายไม่ใช่การแปลซ้ำ แต่บอกว่าคำนี้ใช้ตอนไหน ต่างจากคำใกล้เคียงอย่างไร
หรือมีกับดักตรงไหน ส่วนตัวอย่างประโยคตั้งใจวางในบริบทธุรกิจและบัญชี
ซึ่งเป็นบริบทที่ผู้เรียนคณะบัญชีเจอจริง และใช้ชื่อกิจการสมมติทั้งหมด
"""

GROUPS = [

{'code': 'pair5', 'name': u'คำคู่ 5 กลุ่มหลัก', 'unit': 'Unit 2', 'items': [
 ('marketing mix', u'ส่วนประสมการตลาด · 4P',
  u'สี่ตัวคือ Product Price Place Promotion · เป็นกรอบสำหรับตัดสินใจ ไม่ใช่กิจกรรมเดียว',
  'Every element of the marketing mix carries its own cost.',
  u'ทุกองค์ประกอบของส่วนประสมการตลาดมีต้นทุนของตัวเอง'),
 ('marketing strategy', u'กลยุทธ์การตลาด',
  u'ทิศทางใหญ่ที่ตัดสินก่อน แล้ว plan จึงเขียนตามทีหลัง · เป็นระดับนโยบาย',
  'The board signs off the marketing strategy every March.',
  u'คณะกรรมการอนุมัติกลยุทธ์การตลาดทุกเดือนมีนาคม'),
 ('marketing plan', u'แผนการตลาด',
  u'เอกสารรายละเอียดที่บอกว่าใครทำอะไรเมื่อไรด้วยงบเท่าไร · เขียนหลัง strategy เสมอ',
  'The marketing plan sets out the budget for each quarter.',
  u'แผนการตลาดกำหนดงบประมาณของแต่ละไตรมาสไว้'),
 ('market adaptation', u'การปรับสินค้าให้เข้ากับตลาด',
  u'ปรับตัวสินค้าให้เข้ากับตลาดปลายทาง เช่น รสชาติ ขนาด หรือบรรจุภัณฑ์ · ใช้ STEP ช่วยตัดสิน',
  'Some market adaptation is needed because the recipe is too sweet for that country.',
  u'ต้องปรับสินค้าให้เข้ากับตลาดบ้าง เพราะสูตรหวานเกินไปสำหรับประเทศนั้น'),
 ('market penetration', u'การเจาะตลาด',
  u'เพิ่มส่วนแบ่งในตลาดที่มีอยู่แล้ว ไม่ใช่สร้างตลาดใหม่ · ไม่มี -ing เพราะกระทำต่อตัวตลาด',
  'This is a market penetration problem: we have to take share from someone.',
  u'นี่เป็นโจทย์การเจาะตลาด คือเราต้องแย่งส่วนแบ่งมาจากใครสักราย'),
 ('market segmentation', u'การแบ่งส่วนตลาด',
  u'แบ่งผู้ซื้อออกเป็นกลุ่มที่มีลักษณะร่วมกัน เพื่อคิดต้นทุนและกำไรแยกรายกลุ่มได้ · เป็นคำนามนับไม่ได้ ไม่ใส่ a',
  'Market segmentation lets us cost each group separately.',
  u'การแบ่งส่วนตลาดทำให้เราคิดต้นทุนของแต่ละกลุ่มแยกกันได้'),
 ('product placement', u'การวางสินค้าในสื่อ เช่น ในหนัง',
  u'จ่ายเงินให้สินค้าไปปรากฏในเนื้อหา ไม่ใช่โฆษณาตรง ๆ · อย่าสับสนกับ place ใน 4P',
  'The product placement in that series cost more than a television campaign.',
  u'การวางสินค้าในซีรีส์เรื่องนั้นแพงกว่าแคมเปญทางโทรทัศน์เสียอีก'),
 ('product portfolio', u'กลุ่มผลิตภัณฑ์ทั้งหมดที่บริษัทมี',
  u'มองรวมทุกรายการที่ขาย เพื่อดูว่าตัวไหนทำกำไรและตัวไหนถ่วง',
  'We now sell forty items, and the margin on each one in the product portfolio is different.',
  u'ตอนนี้เราขายสี่สิบรายการ และอัตรากำไรของแต่ละตัวในกลุ่มผลิตภัณฑ์ไม่เท่ากัน'),
 ('product feature', u'คุณสมบัติของสินค้า',
  u'สิ่งที่ตัวสินค้ามี · USP คือ product feature ที่คู่แข่งลอกไม่ได้',
  'The unique selling point is the one product feature no competitor can copy.',
  u'จุดขายที่ไม่เหมือนใครคือคุณสมบัติหนึ่งเดียวที่คู่แข่งลอกไม่ได้'),
 ('customer profile', u'ลักษณะกลุ่มลูกค้า',
  u'ภาพว่าลูกค้าเป็นใคร อายุเท่าไร ซื้อที่ไหน · สร้างจากการวิเคราะห์พฤติกรรมการซื้อจริง',
  'Before we set new credit terms, we need a clearer customer profile.',
  u'ก่อนกำหนดเงื่อนไขการให้สินเชื่อใหม่ เราต้องรู้ลักษณะกลุ่มลูกค้าให้ชัดกว่านี้'),
 ('customer retention', u'การรักษาลูกค้าเดิมไว้',
  u'ถูกกว่าการหาลูกค้าใหม่หลายเท่า จึงเป็นตัวเลขที่ฝ่ายบัญชีต้นทุนใช้บ่อย',
  'Winning a new account costs five times more than customer retention does.',
  u'การได้ลูกค้าใหม่หนึ่งรายแพงกว่าการรักษาลูกค้าเดิมถึงห้าเท่า'),
 ('customer base', u'ฐานลูกค้า',
  u'กลุ่มลูกค้าทั้งหมดที่มีอยู่ · มักใช้กับคำว่า growing หรือ shrinking',
  'A shrinking customer base is the first warning sign in these accounts.',
  u'ฐานลูกค้าที่หดตัวคือสัญญาณเตือนแรกในงบชุดนี้'),
 ('brand positioning', u'การวางตำแหน่งแบรนด์ในใจผู้บริโภค',
  u'ตัดสินว่าจะอยู่ระดับไหน up-market · mid-market · budget แล้วทุกอย่างต้องสอดคล้องกัน',
  'Our brand positioning is premium, so we will not compete on price.',
  u'เราวางตำแหน่งแบรนด์ไว้ระดับพรีเมียม จึงจะไม่แข่งด้วยราคา'),
 ('brand identity', u'อัตลักษณ์แบรนด์ · โลโก้ สี น้ำเสียง',
  u'สิ่งที่บริษัทออกแบบและควบคุมได้ · ต่างจาก brand image ซึ่งอยู่ในใจคนอื่น',
  'The new brand identity uses a single colour across every market.',
  u'อัตลักษณ์แบรนด์ชุดใหม่ใช้สีเดียวกันในทุกตลาด'),
 ('brand extension', u'การต่อยอดแบรนด์ไปสินค้าประเภทใหม่',
  u'ยืมชื่อเสียงของแบรนด์เดิม ต้นทุนสร้างการรับรู้จึงต่ำ แต่เสี่ยงทำให้แบรนด์เดิมเสียถ้าของใหม่ไม่ดี',
  'Selling shampoo under our soap name was a brand extension that cost almost nothing.',
  u'การขายแชมพูภายใต้ชื่อสบู่ของเราคือการต่อยอดแบรนด์ที่แทบไม่มีต้นทุน'),
]},

{'code': 'compound', 'name': u'compound noun', 'unit': 'Unit 2', 'items': [
 ('marketing campaign', u'แคมเปญการตลาด',
  u'ชุดกิจกรรมที่มีเป้าหมายและช่วงเวลาชัดเจน ไม่ใช่การทำต่อเนื่องเรื่อย ๆ',
  'The marketing campaign ran for six weeks and used most of the budget.',
  u'แคมเปญการตลาดดำเนินไปหกสัปดาห์และใช้งบไปเกือบหมด'),
 ('marketing budget', u'งบประมาณการตลาด',
  u'ตัวเลขที่คณะกรรมการอนุมัติ และเป็นสิ่งแรกที่ถูกตัดเมื่อกำไรตก',
  'The board approved the marketing budget but cut the spend by twelve percent.',
  u'คณะกรรมการอนุมัติงบการตลาดแต่ตัดวงเงินลงสิบสองเปอร์เซ็นต์'),
 ('market leader', u'ผู้นำตลาด',
  u'ผู้ที่ครองส่วนแบ่งสูงสุด · ห้ามเขียน marketing leader เด็ดขาด เป็นกับดักที่ออกสอบบ่อย',
  'They hold thirty-one percent of the market, which makes them the market leader.',
  u'พวกเขาครองส่วนแบ่งสามสิบเอ็ดเปอร์เซ็นต์ จึงเป็นผู้นำตลาด'),
 ('market survey', u'การสำรวจตลาด',
  u'เครื่องมือหนึ่งของ market research ไม่ใช่คำเดียวกัน · survey คือวิธี research คืองานทั้งก้อน',
  'The market survey covered sixteen hundred households in three cities.',
  u'การสำรวจตลาดครอบคลุมหนึ่งพันหกร้อยครัวเรือนในสามเมือง'),
 ('market sector', u'ภาคส่วนของตลาด',
  u'แบ่งตามอุตสาหกรรม เช่น ภาคยานยนต์ · ต่างจาก segment ซึ่งแบ่งตามลักษณะผู้ซื้อ',
  'Three firms dominate this market sector.',
  u'สามบริษัทครองภาคส่วนตลาดนี้อยู่'),
 ('product range', u'สายผลิตภัณฑ์ · ช่วงสินค้า',
  u'จำนวนและความหลากหลายของสิ่งที่ขาย · การลดสายผลิตภัณฑ์ช่วยลดต้นทุนการเก็บรักษา',
  'We narrowed the product range from sixty items to twenty to cut holding costs.',
  u'เราลดสายผลิตภัณฑ์จากหกสิบรายการเหลือยี่สิบเพื่อลดต้นทุนการเก็บรักษา'),
 ('product features', u'คุณสมบัติสินค้า',
  u'ใช้รูปพหูพจน์เมื่อพูดถึงหลายคุณสมบัติรวมกัน',
  'Customers rated the product features higher than the price.',
  u'ลูกค้าให้คะแนนคุณสมบัติสินค้าสูงกว่าเรื่องราคา'),
 ('product launch', u'การเปิดตัวสินค้า',
  u'สิ่งที่เลื่อนได้และกระทบประมาณการยอดขายทันที',
  'The product launch was put back by three months, so the sales forecast has to be revised.',
  u'การเปิดตัวสินค้าถูกเลื่อนออกไปสามเดือน ประมาณการยอดขายจึงต้องทำใหม่'),
 ('advertising agency', u'เอเจนซีโฆษณา',
  u'บริษัทภายนอกที่รับทำงานโฆษณาให้ · ค่าบริการมักคิดเป็นเปอร์เซ็นต์ของงบสื่อ',
  'The advertising agency charges a fee based on the media spend.',
  u'เอเจนซีโฆษณาคิดค่าบริการจากยอดใช้จ่ายด้านสื่อ'),
 ('advertising slogan', u'สโลแกนโฆษณา',
  u'ประโยคสั้นที่ใช้ซ้ำจนคนจำได้ · ต่างจาก slogan ทั่วไปตรงที่ผูกกับแคมเปญ',
  'The advertising slogan has not changed in eleven years.',
  u'สโลแกนโฆษณาไม่เคยเปลี่ยนเลยตลอดสิบเอ็ดปี'),
 ('brand awareness', u'การรับรู้แบรนด์',
  u'วัดว่าคนรู้จักแบรนด์ไหม · รู้จักไม่ได้แปลว่าซื้อ ช่องว่างตรงนี้คือโอกาสของผู้มาใหม่',
  'Brand awareness is sixty-one percent, but only forty-one percent actually bought.',
  u'การรับรู้แบรนด์อยู่ที่หกสิบเอ็ดเปอร์เซ็นต์ แต่ซื้อจริงแค่สี่สิบเอ็ด'),
 ('brand loyalty', u'ความภักดีต่อแบรนด์',
  u'วัดจากการกลับมาซื้อซ้ำ · ถ้าลูกค้าเปลี่ยนเจ้าเพราะราคาต่างนิดเดียว แปลว่าความภักดีต่ำ',
  'Buyers switch supplier over a one percent difference, so brand loyalty is very low.',
  u'ผู้ซื้อเปลี่ยนเจ้าเพราะราคาต่างกันหนึ่งเปอร์เซ็นต์ ความภักดีต่อแบรนด์จึงต่ำมาก'),
 ('brand image', u'ภาพลักษณ์แบรนด์',
  u'สิ่งที่อยู่ในใจผู้บริโภค ซึ่งบริษัทควบคุมไม่ได้โดยตรง · เสียได้เร็วกว่าที่สร้าง',
  'Cutting the price would damage our brand image, which took ten years to build.',
  u'การลดราคาจะทำลายภาพลักษณ์แบรนด์ที่ใช้เวลาสร้างสิบปี'),
 ('sales figures', u'ตัวเลขยอดขาย',
  u'sales คงรูปพหูพจน์เสมอ ห้ามเขียน sale figures',
  'The sales figures for the first half were restated after the cut-off error was found.',
  u'ตัวเลขยอดขายครึ่งปีแรกถูกปรับใหม่หลังพบการตัดยอดผิดงวด'),
 ('sales forecast', u'การพยากรณ์ยอดขาย',
  u'ตัวเลขคาดการณ์ที่ผูกกับการวางแผนผลิตและกระแสเงินสด จึงผิดแล้วกระทบทั้งระบบ',
  'The sales forecast assumed the launch would happen in March.',
  u'การพยากรณ์ยอดขายตั้งสมมติฐานว่าจะเปิดตัวในเดือนมีนาคม'),
 ('sales targets', u'เป้าหมายการขาย',
  u'ใช้กับกริยา meet · hit · achieve · miss a target · มักผูกกับโบนัส',
  'None of the four regions met their sales targets, so the bonus provision was reversed.',
  u'ไม่มีภูมิภาคใดในสี่แห่งทำได้ตามเป้าการขาย ประมาณการโบนัสจึงถูกกลับรายการ'),
 ('sales report', u'รายงานการขาย',
  u'เอกสารสรุปผลที่ส่งเป็นงวด · ใช้เป็นฐานของการวิเคราะห์เปรียบเทียบ',
  'The monthly sales report goes to the finance team before the board sees it.',
  u'รายงานการขายรายเดือนส่งถึงฝ่ายการเงินก่อนที่คณะกรรมการจะได้เห็น'),
 ('price promotion', u'การส่งเสริมการขายด้วยราคา',
  u'ลดราคาชั่วคราวเพื่อกระตุ้นยอด · เสี่ยงทำให้ลูกค้ารอซื้อตอนลดอย่างเดียว',
  'A price promotion lifts volume but trains customers to wait for the discount.',
  u'การส่งเสริมการขายด้วยราคาช่วยดันปริมาณ แต่สอนให้ลูกค้ารอส่วนลด'),
 ('price rise', u'การขึ้นราคา',
  u'ใช้เป็นคำนาม · ถ้าเป็นกริยาใช้ prices rose หรือ raise the price',
  'The price rise was announced two weeks before it took effect.',
  u'การขึ้นราคาถูกประกาศล่วงหน้าสองสัปดาห์ก่อนมีผล'),
 ('price range', u'ช่วงราคา',
  u'ตั้งแต่ถูกสุดถึงแพงสุดที่กิจการขาย · ใช้บอกตำแหน่งในตลาดได้',
  'The new line sits at the top of our price range.',
  u'สินค้าสายใหม่อยู่ที่ปลายบนของช่วงราคาของเรา'),
 ('sponsorship deal', u'ข้อตกลงการเป็นผู้สนับสนุน',
  u'สัญญาจ่ายเงินแลกกับการปรากฏชื่อ · ตัวอย่างวลีที่ตำราใช้คือ an excellent sponsorship deal',
  'The club signed an excellent sponsorship deal worth four million a year.',
  u'สโมสรเซ็นข้อตกลงการเป็นผู้สนับสนุนที่ดีมาก มูลค่าปีละสี่ล้าน'),
]},

{'code': 'markets', 'name': u'ตลาดและส่วนของตลาด', 'unit': 'Unit 2', 'items': [
 ('market share', u'ส่วนแบ่งตลาด',
  u'วัดเป็นเปอร์เซ็นต์ของยอดขายรวมในตลาดนั้น · ผูกกับรายได้โดยตรง',
  'Our market share slipped from eighteen percent to fourteen.',
  u'ส่วนแบ่งตลาดของเราลดจากสิบแปดเปอร์เซ็นต์เหลือสิบสี่'),
 ('market segment', u'ส่วนตลาด · กลุ่มผู้ซื้อที่มีลักษณะร่วมกัน',
  u'แบ่งตามลักษณะผู้ซื้อ ไม่ใช่ตามอุตสาหกรรมอย่าง sector',
  'That market segment is small but spends nearly double the average.',
  u'ส่วนตลาดนั้นเล็กแต่ใช้จ่ายเกือบสองเท่าของค่าเฉลี่ย'),
 ('market niche', u'ตลาดเฉพาะกลุ่ม',
  u'เล็กแต่ความต้องการเฉพาะเจาะจง จึงตั้งราคาสูงได้ · สลับเป็น niche market ก็ได้',
  'They found a market niche that the large firms ignore.',
  u'พวกเขาเจอตลาดเฉพาะกลุ่มที่บริษัทใหญ่มองข้าม'),
 ('target market', u'ตลาดเป้าหมาย',
  u'กลุ่มที่ตั้งใจจะขายให้ ซึ่งเลือกมาแล้วจากการแบ่งส่วนตลาด',
  'Office subscription buyers are our target market.',
  u'กลุ่มที่สมัครสมาชิกแบบสำนักงานคือตลาดเป้าหมายของเรา'),
 ('mass market', u'ตลาดมวลชน',
  u'ขายปริมาณมากราคาต่ำ · ตรงข้ามกับ niche ซึ่งขายน้อยแต่ราคาสูง',
  'Moving into the mass market would cut our margin in half.',
  u'การย้ายเข้าสู่ตลาดมวลชนจะทำให้อัตรากำไรของเราเหลือครึ่งเดียว'),
 ('domestic market', u'ตลาดในประเทศ',
  u'ตลาดภายในประเทศของกิจการเอง · เป็นตัวแปลกแยกในแบบฝึก Exercise C ข้อ 4 เพราะอีกสามคำพูดถึงต่างประเทศ',
  'Growth in the domestic market has been flat for three years.',
  u'การเติบโตในตลาดในประเทศทรงตัวมาสามปี'),
 ('overseas market', u'ตลาดต่างประเทศ',
  u'มองจากมุมของประเทศตัวเอง · ใช้สลับกับ foreign market ได้',
  'Half of our revenue now comes from overseas markets.',
  u'ครึ่งหนึ่งของรายได้เรามาจากตลาดต่างประเทศแล้ว'),
 ('international market', u'ตลาดระหว่างประเทศ',
  u'เน้นการค้าข้ามพรมแดนหลายประเทศ ไม่ใช่ประเทศเดียว',
  'Pricing in the international market has to allow for exchange rates.',
  u'การตั้งราคาในตลาดระหว่างประเทศต้องเผื่ออัตราแลกเปลี่ยนไว้'),
 ('worldwide market', u'ตลาดทั่วโลก',
  u'ครอบคลุมทุกภูมิภาค · ใช้กับตัวเลขรวมระดับโลก',
  'The worldwide market for this product is worth nine billion dollars.',
  u'ตลาดทั่วโลกของสินค้านี้มีมูลค่าเก้าพันล้านดอลลาร์'),
 ('growing market', u'ตลาดที่กำลังเติบโต',
  u'โตขึ้นในแง่มูลค่าหรือปริมาณ · ใช้ -ing เพราะกำลังเกิดขึ้นอยู่',
  'It is a growing market, expanding at about nine percent a year.',
  u'เป็นตลาดที่กำลังเติบโต ขยายตัวราวเก้าเปอร์เซ็นต์ต่อปี'),
 ('developing market', u'ตลาดที่กำลังพัฒนา',
  u'ยังไม่อิ่มตัว โครงสร้างการค้ายังเปลี่ยนอยู่ · มักหมายถึงประเทศกำลังพัฒนา',
  'Distribution costs more in a developing market than most plans assume.',
  u'ต้นทุนการกระจายสินค้าในตลาดที่กำลังพัฒนาสูงกว่าที่แผนส่วนใหญ่คาดไว้'),
 ('expanding market', u'ตลาดที่กำลังขยายตัว',
  u'ใกล้เคียงกับ growing market · เน้นที่ขนาดซึ่งกว้างออก',
  'An expanding market attracts new entrants quickly.',
  u'ตลาดที่กำลังขยายตัวดึงดูดผู้เล่นรายใหม่เข้ามาอย่างรวดเร็ว'),
 ('declining market', u'ตลาดที่กำลังหดตัว',
  u'เป็นตัวแปลกแยกในแบบฝึก Exercise C ข้อ 1 เพราะอีกสามคำล้วนบอกการเติบโต',
  'In a declining market, holding share is already an achievement.',
  u'ในตลาดที่กำลังหดตัว แค่รักษาส่วนแบ่งไว้ได้ก็ถือว่าสำเร็จแล้ว'),
 ('up-market', u'ระดับบน · สินค้าราคาแพง',
  u'ตรงข้ามคือ down-market หรือ budget · ใช้เป็น adjective ได้เลย',
  'They moved the brand up-market and raised prices by a fifth.',
  u'พวกเขาย้ายแบรนด์ขึ้นไประดับบนและขึ้นราคาหนึ่งในห้า'),
 ('premium product', u'สินค้าระดับพรีเมียม',
  u'ตั้งราคาสูงกว่าคู่แข่งโดยตั้งใจ และต้องมีเหตุผลรองรับ เช่น คุณภาพวัตถุดิบ',
  'We will position it as a premium product, twenty percent above the average shelf price.',
  u'เราจะวางให้เป็นสินค้าระดับพรีเมียม สูงกว่าราคาเฉลี่ยบนชั้นยี่สิบเปอร์เซ็นต์'),
]},

{'code': 'research', 'name': u'การวิจัยตลาด', 'unit': 'Unit 2', 'items': [
 ('market research', u'การวิจัยตลาด',
  u'ใช้กับกริยา carry out หรือ conduct เท่านั้น ห้ามใช้ make · เป็นงานทั้งก้อน ไม่ใช่เครื่องมือเดียว',
  'The finance committee refused to release the budget until the market research had been completed.',
  u'คณะกรรมการการเงินไม่ยอมอนุมัติงบจนกว่าการวิจัยตลาดจะเสร็จ'),
 ('questionnaire', u'แบบสอบถาม',
  u'เก็บข้อมูลเชิงปริมาณจากคนจำนวนมาก · สะกดยาก ระวังตัว double n',
  'Two thousand buyers completed our questionnaire online.',
  u'ผู้ซื้อสองพันคนกรอกแบบสอบถามของเราทางออนไลน์'),
 ('focus group', u'กลุ่มสนทนา',
  u'เชิญคนไม่กี่คนมานั่งคุยเพื่อเก็บความเห็นเชิงลึก · ได้เหตุผล แต่สรุปกลับไปทั้งตลาดไม่ได้',
  'We ran six focus group sessions and recorded what buyers said about the packaging.',
  u'เราจัดกลุ่มสนทนาหกครั้งและบันทึกสิ่งที่ผู้ซื้อพูดถึงบรรจุภัณฑ์'),
 ('survey', u'การสำรวจ',
  u'ใช้ได้ทั้งคำนามและกริยา · เป็นเครื่องมือหนึ่งใน market research',
  'We surveyed two thousand four hundred households across five provinces.',
  u'เราสำรวจสองพันสี่ร้อยครัวเรือนใน 5 จังหวัด'),
]},

{'code': 'promo', 'name': u'เปิดตัวและส่งเสริมการขาย', 'unit': 'Unit 2', 'items': [
 ('launch a product', u'เปิดตัวสินค้า',
  u'คำที่ใช้บ่อยที่สุดในสามคำนี้ · เน้นการเปิดตัวอย่างเป็นทางการพร้อมกิจกรรม',
  'We plan to launch the product in two cities first.',
  u'เราวางแผนจะเปิดตัวสินค้าในสองเมืองก่อน'),
 ('introduce a product', u'นำสินค้าออกขาย',
  u'กลาง ๆ กว่า launch · ไม่จำเป็นต้องมีงานเปิดตัว',
  'The company introduced a low-sugar version last year.',
  u'บริษัทนำสินค้าสูตรน้ำตาลน้อยออกขายเมื่อปีที่แล้ว'),
 ('bring out a product', u'นำสินค้าออกสู่ตลาด',
  u'เป็นภาษาพูดมากกว่าสองคำแรก · เป็น phrasal verb แยกกันได้ bring it out',
  'They brought out a cheaper model to defend their share.',
  u'พวกเขานำรุ่นราคาถูกกว่าออกสู่ตลาดเพื่อรักษาส่วนแบ่ง'),
 ('withdraw a product', u'ถอนสินค้าออกจากตลาด',
  u'เป็นตัวแปลกแยกในแบบฝึก Exercise C ข้อ 5 เพราะอีกสามคำคือการนำเข้าสู่ตลาด แต่คำนี้คือการเอาออก',
  'The firm withdrew the product after the safety report.',
  u'บริษัทถอนสินค้าออกจากตลาดหลังรายงานด้านความปลอดภัย'),
 ('promotion', u'การส่งเสริมการขาย',
  u'เป็นตัวแปลกแยกในแบบฝึก Exercise C ข้อ 2 · เป็นหนึ่งใน 4P ส่วนคำอื่นในข้อนั้นเป็นเครื่องมือย่อย',
  'Most of the promotion budget went to online video.',
  u'งบส่งเสริมการขายส่วนใหญ่ไปที่วิดีโอออนไลน์'),
 ('special offer', u'ข้อเสนอพิเศษ',
  u'ลดราคาหรือแถมในช่วงเวลาจำกัด · ต้องมีวันสิ้นสุดเสมอ ไม่งั้นกลายเป็นราคาปกติ',
  'The special offer ends on the last day of the month.',
  u'ข้อเสนอพิเศษสิ้นสุดวันสุดท้ายของเดือน'),
 ('free sample', u'สินค้าตัวอย่างแจกฟรี',
  u'ใช้เมื่ออยากให้คนลองก่อนตัดสินใจ · ต้นทุนบันทึกเป็นค่าใช้จ่ายส่งเสริมการขาย',
  'We handed out free samples in eight shopping centres.',
  u'เราแจกสินค้าตัวอย่างฟรีในศูนย์การค้าแปดแห่ง'),
 ('discount', u'ส่วนลด',
  u'ใช้ได้ทั้งคำนามและกริยา · ระวัง give a discount กับ at a discount ความหมายต่างกัน',
  'They offered a ten percent discount for payment within seven days.',
  u'พวกเขาให้ส่วนลดสิบเปอร์เซ็นต์สำหรับการชำระภายในเจ็ดวัน'),
 ('slogan', u'สโลแกน · คำขวัญโฆษณา',
  u'เป็นตัวแปลกแยกในแบบฝึก Exercise C ข้อ 6 เพราะเป็นข้อความ ส่วนคำอื่นเป็นกิจกรรม',
  'The slogan has appeared in every advertisement since two thousand and ten.',
  u'สโลแกนนี้ปรากฏในโฆษณาทุกชิ้นตั้งแต่ปีสองพันสิบ'),
 ('endorsement', u'การรับรองโดยบุคคลมีชื่อเสียง',
  u'มักใช้เป็น celebrity endorsement · เสี่ยงตรงที่ชื่อเสียงของบุคคลนั้นกระทบแบรนด์ด้วย',
  'The celebrity endorsement doubled enquiries in the first week.',
  u'การรับรองโดยคนดังทำให้ยอดสอบถามเพิ่มเป็นสองเท่าในสัปดาห์แรก'),
 ('word of mouth', u'การบอกต่อปากต่อปาก',
  u'ไม่เสียเงินแต่ควบคุมไม่ได้ · เป็นคำนามนับไม่ได้ ไม่ใส่ a',
  'The restaurant spends nothing on advertising and grew entirely through word of mouth.',
  u'ร้านอาหารไม่ใช้เงินโฆษณาเลยและโตขึ้นด้วยการบอกต่อล้วน ๆ'),
 ('point of sale', u'จุดขาย · ณ จุดชำระเงิน',
  u'ย่อว่า POS · หมายถึงตำแหน่งที่เกิดการซื้อจริง ซึ่งเป็นจุดสุดท้ายที่ยังเปลี่ยนใจลูกค้าได้',
  'Display material at the point of sale lifted volume by six percent.',
  u'สื่อจัดแสดง ณ จุดขายช่วยดันปริมาณขึ้นหกเปอร์เซ็นต์'),
]},

{'code': 'channel', 'name': u'ช่องทางจำหน่าย', 'unit': 'Unit 2', 'items': [
 ('retailer', u'ผู้ค้าปลีก',
  u'ขายตรงถึงผู้บริโภคคนสุดท้าย · เป็นด่านที่ตัดสินว่าสินค้าจะได้อยู่บนชั้นหรือไม่',
  'Three retailers control seventy percent of distribution in that country.',
  u'ผู้ค้าปลีกสามรายคุมช่องทางจำหน่ายเจ็ดสิบเปอร์เซ็นต์ในประเทศนั้น'),
 ('wholesaler', u'ผู้ค้าส่ง',
  u'ซื้อจำนวนมากจากผู้ผลิตแล้วกระจายต่อให้ร้านค้าปลีก · อยู่กลางระหว่างสองฝั่ง',
  'The wholesaler takes a margin of about eight percent.',
  u'ผู้ค้าส่งกินส่วนต่างราวแปดเปอร์เซ็นต์'),
 ('distributor', u'ผู้จัดจำหน่าย',
  u'รับสินค้าไปกระจายในพื้นที่หรือประเทศหนึ่ง มักมีสัญญาผูกขาด · ความเสี่ยงคือพึ่งรายเดียว',
  'We do not sell direct; a single distributor handles every order in that country.',
  u'เราไม่ได้ขายตรง แต่มีผู้จัดจำหน่ายรายเดียวดูแลทุกคำสั่งซื้อในประเทศนั้น'),
 ('outlet', u'ร้านจำหน่าย · ช่องทางขาย',
  u'retail outlet คือจุดขายปลีก · นับเป็นจำนวนแห่งได้ จึงใช้รูปพหูพจน์บ่อย',
  'Our distributor supplies eight thousand retail outlets.',
  u'ผู้จัดจำหน่ายของเราส่งสินค้าให้ร้านค้าปลีกแปดพันแห่ง'),
 ('exporter', u'ผู้ส่งออก',
  u'เป็นตัวแปลกแยกในแบบฝึก Exercise C ข้อ 7 เพราะอีกสามคำอยู่ในช่องทางขายภายในประเทศ',
  'The firm began as an exporter before opening its own shops.',
  u'บริษัทเริ่มต้นจากการเป็นผู้ส่งออกก่อนจะเปิดร้านของตัวเอง'),
]},

{'code': 'adverb', 'name': u'adverb ในวลีนาม', 'unit': 'Unit 2', 'items': [
 ('highly', u'อย่างสูง · อย่างยิ่ง',
  u'ใช้กับ adjective ที่มีระดับ เช่น competitive confidential · ต้องอยู่ติดหน้า adjective เสมอ',
  'It is a highly competitive mobile phone market.',
  u'เป็นตลาดโทรศัพท์มือถือที่แข่งขันสูงมาก'),
 ('extremely', u'อย่างที่สุด',
  u'ใช้กับ adjective ที่มีระดับ · แรงกว่า very แต่ยังไม่สุดทางเท่า absolutely',
  'She produced an extremely detailed cost breakdown.',
  u'เธอทำรายละเอียดต้นทุนที่ละเอียดอย่างที่สุด'),
 ('incredibly', u'อย่างเหลือเชื่อ',
  u'เป็นภาษาพูดกว่า extremely · ใช้กับ adjective ที่มีระดับเช่นกัน',
  'The product launch was incredibly successful.',
  u'การเปิดตัวสินค้าประสบความสำเร็จอย่างเหลือเชื่อ'),
 ('absolutely', u'อย่างสมบูรณ์ · สุด ๆ',
  u'ใช้กับ adjective ที่สุดทางแล้วเท่านั้น เช่น brilliant perfect essential · ห้ามใช้ very กับคำกลุ่มนี้',
  'It was an absolutely brilliant global campaign.',
  u'เป็นแคมเปญระดับโลกที่ยอดเยี่ยมสุด ๆ'),
 ('really', u'จริง ๆ · มาก',
  u'ใช้ได้กับ adjective ทั้งสองแบบ จึงปลอดภัยที่สุดเวลาไม่แน่ใจ',
  'They ran a really impressive advertising campaign.',
  u'พวกเขาทำแคมเปญโฆษณาที่น่าประทับใจจริง ๆ'),
 ('increasingly', u'มากขึ้นเรื่อย ๆ',
  u'บอกแนวโน้มที่เปลี่ยนไปตามเวลา ไม่ใช่ระดับ ณ จุดเดียว',
  'We operate in an increasingly competitive marketing environment.',
  u'เราอยู่ในสภาพแวดล้อมทางการตลาดที่แข่งขันสูงขึ้นเรื่อย ๆ'),
 ('totally', u'ทั้งหมด · โดยสิ้นเชิง',
  u'ใช้กับ adjective ที่สุดทางแล้ว กลุ่มเดียวกับ absolutely',
  'The two sets of figures are totally different.',
  u'ตัวเลขสองชุดนี้ต่างกันโดยสิ้นเชิง'),
 ('fairly', u'ค่อนข้าง',
  u'อ่อนกว่า very · ใช้เมื่ออยากชมแบบมีเงื่อนไข ซึ่งบางครั้งฟังเหมือนไม่ค่อยชม',
  'The response rate was fairly low at twenty-three percent.',
  u'อัตราการตอบกลับค่อนข้างต่ำ อยู่ที่ยี่สิบสามเปอร์เซ็นต์'),
]},

{'code': 'phrase', 'name': u'วลีนามจากบทความ', 'unit': 'Unit 2', 'items': [
 ('an advertising campaign', u'แคมเปญโฆษณา',
  u'นิยามในบทความคือชุดกิจกรรมที่จัดขึ้นเพื่อโน้มน้าวให้คนซื้อ · a programme of activities to persuade the public to buy',
  'The advertising campaign used most of the promotion budget.',
  u'แคมเปญโฆษณาใช้งบส่งเสริมการขายไปเกือบหมด'),
 ('chief executive', u'ประธานเจ้าหน้าที่บริหาร',
  u'ผู้มีตำแหน่งสูงสุดในฝ่ายบริหาร ย่อว่า CEO · the person with the highest position',
  'The chief executive presented the results to analysts.',
  u'ประธานเจ้าหน้าที่บริหารนำเสนอผลประกอบการต่อนักวิเคราะห์'),
 ('fashion houses', u'ห้องเสื้อ · แบรนด์แฟชั่น',
  u'ผู้ผลิตเสื้อผ้าที่ออกแบบตามกระแสซึ่งเปลี่ยนตลอด · the makers of clothes in new and changing styles',
  'The largest fashion houses now sell more accessories than clothes.',
  u'ห้องเสื้อรายใหญ่ที่สุดขายเครื่องประดับมากกว่าเสื้อผ้าไปแล้ว'),
 ('a luxury goods company', u'บริษัทสินค้าหรูหรา',
  u'ผลิตของแพงที่ซื้อเพื่อความสบายและความพึงพอใจ · makes expensive things for comfort and pleasure',
  'A luxury goods company protects its margin rather than its volume.',
  u'บริษัทสินค้าหรูหราปกป้องอัตรากำไรมากกว่าปริมาณขาย'),
 ('growth potential', u'ศักยภาพในการเติบโต',
  u'ความเป็นไปได้ที่จะพัฒนาและขยายตัวในอนาคต · possibility for future development and expansion',
  'The region has real growth potential but weak distribution.',
  u'ภูมิภาคนี้มีศักยภาพในการเติบโตจริง แต่ช่องทางจำหน่ายยังอ่อน'),
]},

{'code': 'abbr', 'name': u'ตัวย่อ', 'unit': 'Unit 2', 'items': [
 ('SWOT', u'จุดแข็ง จุดอ่อน โอกาส อุปสรรค',
  u'Strengths Weaknesses Opportunities Threats · วิเคราะห์ตัวบริษัทเอง สองตัวแรกมาจากภายใน สองตัวหลังมาจากภายนอก',
  'The SWOT analysis showed our weakness is distribution, not price.',
  u'การวิเคราะห์ SWOT ชี้ว่าจุดอ่อนของเราคือช่องทางจำหน่าย ไม่ใช่ราคา'),
 ('STEP · PEST', u'สังคม เทคโนโลยี เศรษฐกิจ การเมือง',
  u'Sociological Technological Economic Political · วิเคราะห์ปัจจัยภายนอกล้วน จึงต่างจาก SWOT',
  'A STEP analysis helps decide how much market adaptation is needed.',
  u'การวิเคราะห์ STEP ช่วยตัดสินว่าต้องปรับสินค้าให้เข้ากับตลาดมากแค่ไหน'),
 ('USP', u'จุดขายที่ไม่เหมือนใคร',
  u'Unique Selling Point · ต้องเป็นสิ่งที่คู่แข่งลอกไม่ได้จริง ไม่ใช่แค่ข้อดีทั่วไป',
  'Our USP is the ingredient quality, which no competitor can match.',
  u'จุดขายที่ไม่เหมือนใครของเราคือคุณภาพวัตถุดิบ ซึ่งไม่มีคู่แข่งรายใดเทียบได้'),
 ('4P', u'ส่วนประสมการตลาดสี่ตัว',
  u'Product Price Place Promotion · เป็นกรอบเดียวกับ marketing mix',
  'Each of the 4P decisions has a cost that appears somewhere in the accounts.',
  u'การตัดสินใจในแต่ละตัวของ 4P มีต้นทุนที่ไปปรากฏอยู่ที่ใดที่หนึ่งในบัญชี'),
]},

]
